apiVersion: v1
kind: Schema
metadata:
  name: devopsmaestro-database
  version: 1.0.0  # The version of the schema
spec:
  dbTypes:
    sqlite:
      migrations:
        - name: "0001_initial_schema"
          description: "Initial schema creation for SQLite"
          up: "sqlite/0001_initial_schema.up.sql"
          down: "sqlite/0001_initial_schema.down.sql"
        - name: "0002_mvp_schema"
          description: "Add workspaces, context tables and project path"
          up: "sqlite/0002_mvp_schema.up.sql"
          down: "sqlite/0002_mvp_schema.down.sql"

    postgres:
      migrations:
        - name: "0001_initial_schema"
          description: "Initial schema creation for PostgreSQL"
          up: "postgres/0001_initial_schema.up.sql"
          down: "postgres/0001_initial_schema.down.sql"