# GoReleaser configuration for DevOpsMaestro
# https://goreleaser.com

version: 2

# Run before the build to set up completions directory
before:
  hooks:
    - go mod tidy

# Build configuration
builds:
  # Main dvm binary
  - id: dvm
    binary: dvm
    main: .
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.Commit={{.ShortCommit}}
    goos:
      - darwin
    goarch:
      - arm64
    # Note: Only building darwin/arm64 for now
    # Linux builds require cross-compilation toolchains that aren't available locally
    # To add linux support, use GitHub Actions with appropriate runners
    hooks:
      post:
        # Skip completion generation for dvm on GitHub runner (darwin binary can't run on linux)
        # Completions will be generated locally or during local release
        - cmd: sh -c 'echo "Skipping dvm completions (cross-compiled binary)"'
          output: true

  # nvp (NvimOps) binary - standalone Neovim plugin manager
  - id: nvp
    binary: nvp
    main: ./cmd/nvp
    env:
      - CGO_ENABLED=0  # nvp doesn't need CGO (no sqlite)
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.Commit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    hooks:
      post:
        # Generate shell completions ONLY for linux_amd64 (native on GitHub runner)
        # Other platforms can't run their binaries on the linux runner
        - cmd: sh -c '[ "{{ .Os }}" = "linux" ] && [ "{{ .Arch }}" = "amd64" ] && mkdir -p dist/completions/nvp && {{ .Path }} completion bash > dist/completions/nvp/nvp.bash && {{ .Path }} completion zsh > dist/completions/nvp/_nvp && {{ .Path }} completion fish > dist/completions/nvp/nvp.fish || true'
          output: true

# Archive configuration
archives:
  # dvm archive (darwin only for now)
  - id: dvm-archive
    ids:
      - dvm
    name_template: >-
      dvm_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**/*

  # nvp archive (cross-platform)
  - id: nvp-archive
    ids:
      - nvp
    name_template: >-
      nvp_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - NVIMOPS_TEST_PLAN.md
      - src: dist/completions/nvp/*
        dst: completions
        strip_parent: true

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshots (for testing releases)
snapshot:
  version_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: '📝 Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: '🔧 Other'
      order: 999

# GitHub Release
release:
  github:
    owner: rmkohlman
    name: devopsmaestro
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## DevOpsMaestro {{ .Tag }}
    
    Welcome to this new release of DevOpsMaestro!
    
    This release includes two binaries:
    - **dvm** - Development workspace manager (macOS only)
    - **nvp** - NvimOps plugin manager (cross-platform)
  footer: |
    ---
    
    ## Installation
    
    ### dvm (macOS - Homebrew)
    ```bash
    brew install rmkohlman/tap/dvm
    ```
    
    ### nvp (Cross-platform)
    Download the appropriate `nvp_*` archive for your platform from the assets below.
    
    **Quick start with nvp:**
    ```bash
    nvp library list              # See available plugins
    nvp library install telescope # Install from library
    nvp generate                  # Generate Lua files
    ```
    
    Shell completions are included in the `completions/` directory of each archive.
    
    **Full Changelog**: https://github.com/rmkohlman/devopsmaestro/blob/main/CHANGELOG.md

# Homebrew Casks - GoReleaser will update the tap automatically
# Note: Casks are the recommended way for distributing pre-built binaries
homebrew_casks:
  # dvm Cask (macOS only, requires CGO)
  - repository:
      owner: rmkohlman
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    ids:
      - dvm-archive
    name: dvm
    commit_author:
      name: Robert Kohlman
      email: rkohlman@users.noreply.github.com
    homepage: https://github.com/rmkohlman/devopsmaestro
    description: "DevOpsMaestro (dvm) - CLI tool for managing development workspaces"
    license: "GPL-3.0"
    url:
      verified: github.com/rmkohlman/devopsmaestro
    skip_upload: true  # We maintain the cask manually
    binaries:
      - dvm
    hooks:
      post:
        # Remove quarantine attribute for unsigned binary
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dvm"]
          end

  # nvp Cask (cross-platform, no CGO needed)
  - repository:
      owner: rmkohlman
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    ids:
      - nvp-archive
    name: nvp
    commit_author:
      name: Robert Kohlman
      email: rkohlman@users.noreply.github.com
    homepage: https://github.com/rmkohlman/devopsmaestro
    description: "nvp (NvimOps) - DevOps-style Neovim plugin manager"
    license: "GPL-3.0"
    url:
      verified: github.com/rmkohlman/devopsmaestro
    skip_upload: true  # We maintain the cask manually
    binaries:
      - nvp
    zap:
      trash:
        - "~/.nvp"
    hooks:
      post:
        # Remove quarantine attribute for unsigned binary
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nvp"]
          end

# Announcement
announce:
  skip: true

# Sign artifacts (disabled - requires GPG key)
# signs:
#   - artifacts: checksum
#     signature: "${artifact}.sig"
