# GoReleaser configuration for DevOpsMaestro
# https://goreleaser.com

version: 2

# Run before the build to set up completions directory
before:
  hooks:
    - go mod tidy

# Build configuration
builds:
  - id: dvm
    binary: dvm
    main: .
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.Commit={{.ShortCommit}}
    goos:
      - darwin
    goarch:
      - arm64
    # Note: Only building darwin/arm64 for now
    # Linux builds require cross-compilation toolchains that aren't available locally
    # To add linux support, use GitHub Actions with appropriate runners
    hooks:
      post:
        # Generate shell completions after the native build
        # This runs after each build, but completions are identical across platforms
        - cmd: sh -c 'mkdir -p dist/completions && {{ .Path }} completion bash > dist/completions/dvm.bash && {{ .Path }} completion zsh > dist/completions/_dvm && {{ .Path }} completion fish > dist/completions/dvm.fish'
          output: true

# Archive configuration
archives:
  - id: dvm-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**/*
      - src: dist/completions/*
        dst: completions
        strip_parent: true

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshots (for testing releases)
snapshot:
  version_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: '📝 Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: '🔧 Other'
      order: 999

# GitHub Release
release:
  github:
    owner: rmkohlman
    name: devopsmaestro
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## DevOpsMaestro {{ .Tag }}
    
    Welcome to this new release of DevOpsMaestro!
  footer: |
    ---
    
    ## Installation
    
    ### macOS (Homebrew)
    ```bash
    brew install rmkohlman/tap/dvm
    ```
    
    Shell completions are automatically installed for bash, zsh, and fish.
    
    ### Binary Download
    Download the appropriate binary for your platform from the assets below.
    The archive includes shell completion files in the `completions/` directory.
    
    **Full Changelog**: https://github.com/rmkohlman/devopsmaestro/blob/main/CHANGELOG.md

# Homebrew tap - GoReleaser will update this automatically
# But we maintain our own formula manually for more control
brews:
  - repository:
      owner: rmkohlman
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: Robert Kohlman
      email: rkohlman@users.noreply.github.com
    homepage: https://github.com/rmkohlman/devopsmaestro
    description: "DevOpsMaestro (dvm) - CLI tool for managing development workspaces"
    license: "GPL-3.0"
    directory: Formula
    skip_upload: true  # We maintain the formula manually
    install: |
      bin.install "dvm"
    test: |
      system "#{bin}/dvm", "version"

# Announcement
announce:
  skip: true

# Sign artifacts (disabled - requires GPG key)
# signs:
#   - artifacts: checksum
#     signature: "${artifact}.sig"
