# GoReleaser configuration for DevOpsMaestro
# https://goreleaser.com
#
# NOTE: This only builds nvp (NvimOps) since it doesn't require CGO.
# dvm is built separately on macOS runners (see .github/workflows/release.yml)

version: 2

before:
  hooks:
    - go mod tidy

builds:
  # nvp (NvimOps) binary - standalone Neovim plugin manager
  # No CGO required, can cross-compile on Linux
  - id: nvp
    binary: nvp
    main: ./cmd/nvp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.Commit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    hooks:
      post:
        # Generate shell completions for linux_amd64 (native on GitHub runner)
        - cmd: sh -c '[ "{{ .Os }}" = "linux" ] && [ "{{ .Arch }}" = "amd64" ] && mkdir -p dist/completions/nvp && {{ .Path }} completion bash > dist/completions/nvp/nvp.bash && {{ .Path }} completion zsh > dist/completions/nvp/_nvp && {{ .Path }} completion fish > dist/completions/nvp/nvp.fish || true'
          output: true

archives:
  - id: nvp-archive
    ids:
      - nvp
    name_template: >-
      nvp_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - src: dist/completions/nvp/*
        dst: completions
        strip_parent: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: '📝 Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: '🔧 Other'
      order: 999

release:
  github:
    owner: rmkohlman
    name: devopsmaestro
  draft: false
  prerelease: auto
  mode: append  # Append to existing release (dvm builds add their artifacts too)
  header: |
    ## DevOpsMaestro {{ .Tag }}
    
    This release includes:
    - **dvm** (DevOpsMaestro) - Workspace management CLI (macOS)
    - **dvt** (TerminalOps) - Terminal configuration management CLI (macOS)
    - **nvp** (NvimOps) - Neovim plugin manager (cross-platform)
  footer: |
    ---
    
    ## Installation
    
    ### Homebrew (Recommended)
    ```bash
    brew tap rmkohlman/tap
    brew install devopsmaestro  # Installs dvm
    brew install terminalops    # Installs dvt
    brew install nvimops        # Installs nvp (standalone)
    ```
    
    ### Manual Download
    Download the appropriate archive for your platform from the assets below.
    
    **Quick start with dvm:**
    ```bash
    dvm admin init
    dvm create app myapp --from-cwd
    dvm build
    dvm attach
    ```
    
    **Quick start with dvt:**
    ```bash
    dvt init
    dvt prompt library install starship-default
    dvt plugin library install zsh-autosuggestions
    dvt profile generate
    ```
    
    **Quick start with nvp:**
    ```bash
    nvp init
    nvp library list
    nvp library install telescope
    nvp generate
    ```
    
    **Full Changelog**: https://github.com/rmkohlman/devopsmaestro/blob/main/CHANGELOG.md

announce:
  skip: true
