# GoReleaser configuration for DevOpsMaestro
# https://goreleaser.com

version: 2

# Build configuration
builds:
  - id: dvm
    binary: dvm
    main: .
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.Commit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    # Skip combinations that require cross-compilation toolchains
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
        # For now, only build for the native platform in CI

# Archive configuration
archives:
  - id: dvm-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**/*

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshots (for testing releases)
snapshot:
  version_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
  groups:
    - title: 'ðŸš€ Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'ðŸ› Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'ðŸ“ Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'ðŸ”§ Other'
      order: 999

# GitHub Release
release:
  github:
    owner: rmkohlman
    name: devopsmaestro
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## DevOpsMaestro {{ .Tag }}
    
    Welcome to this new release of DevOpsMaestro!
  footer: |
    ---
    
    ## Installation
    
    ### macOS (Homebrew)
    ```bash
    brew tap rmkohlman/tap
    brew install dvm
    ```
    
    ### Binary Download
    Download the appropriate binary for your platform from the assets below.
    
    ### Shell Completion
    After installing, set up shell completion:
    ```bash
    # Zsh (macOS)
    dvm completion zsh > $(brew --prefix)/share/zsh/site-functions/_dvm
    
    # Bash (macOS)
    dvm completion bash > $(brew --prefix)/etc/bash_completion.d/dvm
    ```
    
    **Full Changelog**: https://github.com/rmkohlman/devopsmaestro/blob/main/CHANGELOG.md

# Homebrew tap
brews:
  - repository:
      owner: rmkohlman
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: Robert Kohlman
      email: rkohlman@users.noreply.github.com
    homepage: https://github.com/rmkohlman/devopsmaestro
    description: "DevOpsMaestro (dvm) - CLI tool for managing development workspaces"
    license: "GPL-3.0"
    directory: Formula
    install: |
      bin.install "dvm"
      
      # Generate and install shell completions
      generate_completions_from_executable(bin/"dvm", "completion")
    test: |
      system "#{bin}/dvm", "version"

# Announcement
announce:
  skip: true

# Sign artifacts (optional - requires GPG key)
signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
