package prompt

import (
	"strings"
	"testing"
)

func TestStarshipGenerator_Generate(t *testing.T) {
	g := NewStarshipGenerator()

	p := &Prompt{
		Name:        "my-prompt",
		Description: "A test prompt",
		Type:        PromptTypeStarship,
		Format:      "$directory$git_branch$character",
		Character: &CharacterConfig{
			SuccessSymbol: "[❯](green)",
			ErrorSymbol:   "[❯](red)",
		},
		Modules: map[string]ModuleConfig{
			"directory": {
				Options: map[string]any{
					"truncation_length": 3,
				},
			},
			"git_branch": {
				Format: "[$branch]($style) ",
				Style:  "bold purple",
			},
		},
	}

	output, err := g.Generate(p)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	t.Logf("Generated output:\n%s", output)

	// Check header
	if !strings.Contains(output, "# Starship configuration generated by DevOpsMaestro") {
		t.Error("expected header comment")
	}
	if !strings.Contains(output, "Prompt: my-prompt") {
		t.Error("expected prompt name in header")
	}

	// Check format (TOML library uses single quotes)
	if !strings.Contains(output, `format = '$directory$git_branch$character'`) {
		t.Error("expected format in output")
	}

	// Check character config
	if !strings.Contains(output, `success_symbol = '[❯](green)'`) {
		t.Error("expected success_symbol in output")
	}
	if !strings.Contains(output, `error_symbol = '[❯](red)'`) {
		t.Error("expected error_symbol in output")
	}
}

func TestStarshipGenerator_Generate_RawConfig(t *testing.T) {
	g := NewStarshipGenerator()

	rawConfig := `# Custom config
format = "$all"
[character]
success_symbol = ">"
`

	p := &Prompt{
		Name:      "raw-prompt",
		Type:      PromptTypeStarship,
		RawConfig: rawConfig,
	}

	output, err := g.Generate(p)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	if output != rawConfig {
		t.Errorf("expected raw config to be returned unchanged, got %s", output)
	}
}

func TestStarshipGenerator_Generate_WrongType(t *testing.T) {
	g := NewStarshipGenerator()

	p := &Prompt{
		Name: "p10k-prompt",
		Type: PromptTypePowerlevel10k,
	}

	_, err := g.Generate(p)
	if err == nil {
		t.Error("expected error for non-starship prompt")
	}
}

func TestStarshipGenerator_Generate_Nil(t *testing.T) {
	g := NewStarshipGenerator()

	_, err := g.Generate(nil)
	if err == nil {
		t.Error("expected error for nil prompt")
	}
}

func TestStarshipGenerator_GenerateMinimal(t *testing.T) {
	g := NewStarshipGenerator()

	output := g.GenerateMinimal()

	if !strings.Contains(output, "format =") {
		t.Error("expected format in minimal config")
	}
	if !strings.Contains(output, "[directory]") {
		t.Error("expected directory section in minimal config")
	}
	if !strings.Contains(output, "[character]") {
		t.Error("expected character section in minimal config")
	}
}

func TestDefaultModules(t *testing.T) {
	modules := DefaultModules()

	// Check directory module
	dir, ok := modules["directory"]
	if !ok {
		t.Fatal("expected directory module")
	}
	if dir.Options["truncation_length"] != 3 {
		t.Error("expected truncation_length of 3")
	}

	// Check git_branch module
	git, ok := modules["git_branch"]
	if !ok {
		t.Fatal("expected git_branch module")
	}
	if git.Style != "bold purple" {
		t.Errorf("expected style 'bold purple', got %s", git.Style)
	}

	// Check kubernetes is disabled by default
	k8s, ok := modules["kubernetes"]
	if !ok {
		t.Fatal("expected kubernetes module")
	}
	if !k8s.Disabled {
		t.Error("expected kubernetes module to be disabled by default")
	}
}

func TestFormatWithColors(t *testing.T) {
	tests := []struct {
		text     string
		color    string
		expected string
	}{
		{"❯", "green", "[❯](green)"},
		{"❯", "bold red", "[❯](bold red)"},
		{"❯", "", "❯"},
	}

	for _, tt := range tests {
		result := FormatWithColors(tt.text, tt.color)
		if result != tt.expected {
			t.Errorf("FormatWithColors(%q, %q): expected %q, got %q", tt.text, tt.color, tt.expected, result)
		}
	}
}

func TestBuildFormat(t *testing.T) {
	tests := []struct {
		modules  []string
		expected string
	}{
		{[]string{"directory", "character"}, "$directory$character"},
		{[]string{"directory", "git_branch", "character"}, "$directory$git_branch$character"},
		{[]string{}, ""},
	}

	for _, tt := range tests {
		result := BuildFormat(tt.modules...)
		if result != tt.expected {
			t.Errorf("BuildFormat(%v): expected %q, got %q", tt.modules, tt.expected, result)
		}
	}
}
