apiVersion: devopsmaestro.io/v1
kind: NvimTheme
metadata:
  name: coolnight-synthwave
  description: CoolNight Synthwave - Neon purple inspired by 80s aesthetics
  author: DevOpsMaestro (parametric generator)
  category: dark
spec:
  plugin:
    repo: "rmkohlman/coolnight.nvim"
  style: synthwave
  transparent: false
  colors:
    # Nvim colors (shifted to hue 270° from 210°)
    bg: "#1A0128"           # Main background (purple shifted)
    bg_dark: "#150123"      # Darker background
    bg_highlight: "#36145C" # Selection highlight (purple)
    bg_visual: "#4B2778"    # Visual selection (purple)
    bg_search: "#6A0AAC"    # Search highlight (purple)
    fg: "#E0CBF0"           # Main foreground (purple tint)
    fg_dark: "#D0B4E9"      # Darker foreground
    fg_gutter: "#7E6297"    # Gutter text (purple)
    border: "#7954B8"       # Border color (purple)
    
    # Syntax colors
    comment: "#7E6297"      # Same as fg_gutter
    red: "#E52E2E"          # ANSI red (fixed semantic)
    green: "#44FFB1"        # ANSI green (fixed semantic)
    yellow: "#FFE073"       # ANSI yellow (fixed semantic)
    blue: "#8D0CED"         # ANSI blue (shifted to purple)
    magenta: "#FF77A2"      # ANSI magenta (shifted)
    cyan: "#F724EA"         # ANSI cyan (shifted to pink)
    orange: "#FFE073"       # Same as yellow
    purple: "#FF77A2"       # Same as magenta
    
    # Terminal ANSI colors
    ansi_black: "#492169"
    ansi_red: "#E52E2E"     # Fixed semantic
    ansi_green: "#44FFB1"   # Fixed semantic
    ansi_yellow: "#FFE073"  # Fixed semantic
    ansi_blue: "#8D0CED"    # Purple shifted
    ansi_magenta: "#FF77A2" # Pink shifted
    ansi_cyan: "#F724EA"    # Pink shifted
    ansi_white: "#F724EA"
    ansi_bright_black: "#492169"
    ansi_bright_red: "#E52E2E"
    ansi_bright_green: "#44FFB1"
    ansi_bright_yellow: "#FFE073"
    ansi_bright_blue: "#FF77A2"
    ansi_bright_magenta: "#FF77A2"
    ansi_bright_cyan: "#F724EA"
    ansi_bright_white: "#F724EA"
    
    # Terminal UI colors
    cursor: "#47FF9C"       # Green cursor (fixed)
    cursor_text: "#150123"  # Same as bg_dark
    selection: "#251832"    # Darker purple
    selection_text: "#E0CBF0" # Same as fg
    
    # Diagnostic colors
    error: "#E52E2E"        # Same as red
    warning: "#FFE073"      # Same as yellow
    info: "#8D0CED"         # Same as blue
    hint: "#44FFB1"         # Same as green
    success: "#44FFB1"      # Same as green
  options:
    styles:
      comments: italic
      keywords: bold
      functions: NONE
      variables: NONE