apiVersion: devopsmaestro.io/v1
kind: NvimTheme
metadata:
  name: coolnight-grape
  description: CoolNight Grape - Rich grape purple
  author: DevOpsMaestro (parametric generator)
  category: dark
spec:
  plugin:
    repo: "rmkohlman/coolnight.nvim"
  style: grape
  transparent: false
  colors:
    # Nvim colors (exact from parametric generator)
    bg: "#200028"           # Main background
    bg_dark: "#1b0023"      # Darker background  
    bg_highlight: "#441452" # Selection highlight
    bg_search: "#8809ac"    # Search highlight
    bg_visual: "#662678"    # Visual selection
    fg: "#e7cbf0"           # Main foreground
    fg_dark: "#deb4e8"      # Darker foreground
    fg_gutter: "#8c6297"    # Gutter text
    border: "#895398"       # Border color
    
    # Syntax colors (derived from ANSI)
    comment: "#8c6297"      # Same as fg_gutter
    red: "#E52E2E"          # ANSI red
    green: "#44FFB1"        # ANSI green  
    yellow: "#FFE073"       # ANSI yellow
    blue: "#810fed"         # ANSI blue
    magenta: "#ff77a6"      # ANSI magenta
    cyan: "#7723f7"         # ANSI cyan
    orange: "#FFE073"       # Same as yellow
    purple: "#ff77a6"       # Same as magenta
    
    # Terminal ANSI colors (exact from parametric generator)
    ansi_black: "#592069"
    ansi_red: "#E52E2E"
    ansi_green: "#44FFB1"
    ansi_yellow: "#FFE073"
    ansi_blue: "#810fed"
    ansi_magenta: "#ff77a6"
    ansi_cyan: "#7723f7"
    ansi_white: "#7723f7"
    ansi_bright_black: "#592069"
    ansi_bright_red: "#E52E2E"
    ansi_bright_green: "#44FFB1"
    ansi_bright_yellow: "#FFE073"
    ansi_bright_blue: "#ff77a6"
    ansi_bright_magenta: "#ff77a6"
    ansi_bright_cyan: "#7723f7"
    ansi_bright_white: "#7723f7"
    
    # Terminal UI colors
    cursor: "#47FF9C"       # Green cursor
    cursor_text: "#1b0023"  # Same as bg_dark
    selection: "#460359"    # Darker than bg_visual
    selection_text: "#e7cbf0" # Same as fg
    
    # Diagnostic colors
    error: "#E52E2E"        # Same as red
    warning: "#FFE073"      # Same as yellow
    info: "#810fed"         # Same as blue
    hint: "#44FFB1"         # Same as green
    success: "#44FFB1"      # Same as green
  options:
    styles:
      comments: italic
      keywords: bold
      functions: NONE
      variables: NONE