apiVersion: devopsmaestro.io/v1
kind: NvimTheme
metadata:
  name: coolnight-sunset
  description: CoolNight Sunset - Warm orange sunset tones
  author: DevOpsMaestro (parametric generator)
  category: dark
spec:
  plugin:
    repo: ""  # Standalone theme - no external plugin required
  style: sunset
  transparent: false
  colors:
    # Nvim colors (exact from parametric generator)
    bg: "#280f00"           # Main background
    bg_dark: "#230d00"      # Darker background  
    bg_highlight: "#522a14" # Selection highlight
    bg_search: "#ac4409"    # Search highlight
    bg_visual: "#784526"    # Visual selection
    fg: "#f0d7cb"           # Main foreground
    fg_dark: "#e8c8b4"      # Darker foreground
    fg_gutter: "#977662"    # Gutter text
    border: "#986d53"       # Border color
    
    # Syntax colors (derived from ANSI)
    comment: "#977662"      # Same as fg_gutter
    red: "#E52E2E"          # ANSI red
    green: "#44FFB1"        # ANSI green  
    yellow: "#FFE073"       # ANSI yellow
    blue: "#ed240f"         # ANSI blue
    magenta: "#dfff77"      # ANSI magenta
    cyan: "#f72328"         # ANSI cyan
    orange: "#FFE073"       # Same as yellow
    purple: "#dfff77"       # Same as magenta
    
    # Terminal ANSI colors (exact from parametric generator)
    ansi_black: "#693b20"
    ansi_red: "#E52E2E"
    ansi_green: "#44FFB1"
    ansi_yellow: "#FFE073"
    ansi_blue: "#ed240f"
    ansi_magenta: "#dfff77"
    ansi_cyan: "#f72328"
    ansi_white: "#f72328"
    ansi_bright_black: "#693b20"
    ansi_bright_red: "#E52E2E"
    ansi_bright_green: "#44FFB1"
    ansi_bright_yellow: "#FFE073"
    ansi_bright_blue: "#dfff77"
    ansi_bright_magenta: "#dfff77"
    ansi_bright_cyan: "#f72328"
    ansi_bright_white: "#f72328"
    
    # Terminal UI colors
    cursor: "#47FF9C"       # Green cursor
    cursor_text: "#230d00"  # Same as bg_dark
    selection: "#592203"    # Darker than bg_visual
    selection_text: "#f0d7cb" # Same as fg
    
    # Diagnostic colors
    error: "#E52E2E"        # Same as red
    warning: "#FFE073"      # Same as yellow
    info: "#ed240f"         # Same as blue
    hint: "#44FFB1"         # Same as green
    success: "#44FFB1"      # Same as green
  options:
    styles:
      comments: italic
      keywords: bold
      functions: NONE
      variables: NONE