apiVersion: devopsmaestro.io/v1
kind: PromptExtension
metadata:
  name: character
  description: Prompt character with vim mode support
  category: system
  tags:
    - character
    - prompt
    - vim
spec:
  segment: character
  provides:
    - line_break
    - character
  modules:
    line_break:
      disabled: false
    character:
      disabled: false
      options:
        success_symbol: "[❯](bold fg:green)"
        error_symbol: "[❯](bold fg:red)"
        vimcmd_symbol: "[❮](bold fg:green)"
        vimcmd_replace_one_symbol: "[❮](bold fg:lavender)"
        vimcmd_replace_symbol: "[❮](bold fg:lavender)"
        vimcmd_visual_symbol: "[❮](bold fg:yellow)"
