apiVersion: devopsmaestro.io/v1
kind: PromptExtension
metadata:
  name: identity
  description: OS icon and username display
  category: system
  tags:
    - os
    - username
    - identity
spec:
  segment: identity
  provides:
    - os
    - username
  modules:
    os:
      disabled: false
      style: "bg:red fg:crust"
      options:
        symbols:
          Macos: "  "
          Windows: ""
          Ubuntu: "󰕈"
          SUSE: ""
          Arch: ""
          CentOS: ""
          Debian: "󰣚"
          Redhat: " "
    username:
      show_always: true
      style_user: "bg:red fg:crust"
      style_root: "bg:red fg:crust"
      format: "[$user]($style)"
      options:
        aliases:
          rkohlman: "🙎🏻‍♂️"
