apiVersion: devopsmaestro.io/v1
kind: PromptExtension
metadata:
  name: languages-all
  description: All programming language version displays
  category: development
  tags:
    - languages
    - nodejs
    - python
    - rust
    - golang
spec:
  segment: languages
  provides:
    - c
    - rust
    - golang
    - nodejs
    - php
    - java
    - kotlin
    - haskell
    - python
    - custom.db
  modules:
    c:
      symbol: " "
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    rust:
      symbol: ""
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    golang:
      symbol: ""
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    nodejs:
      symbol: ""
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    php:
      symbol: ""
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    java:
      symbol: " "
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    kotlin:
      symbol: ""
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    haskell:
      symbol: ""
      style: "bg:green"
      format: "[[ $symbol( $version) ](fg:crust bg:green)]($style)"
    python:
      symbol: ""
      style: "bg:green"
      format: "[[ $symbol( $version)(\\(#$virtualenv\\)) ](fg:crust bg:green)]($style)"
    custom.db:
      symbol: "󰆼"
      format: "[[ $symbol( $version)(\\(#$virtualenv\\)) ](fg:crust bg:green)]($style)"
      options:
        detect_extensions:
          - sql
          - ddl
          - dml
          - mdf
          - ndf
          - ldf
          - db
          - sqlite
          - sqlite3
          - mdb
          - accdb
          - frm
          - myd
          - myi
          - ibd
          - dbf
          - gdb
          - fdb
          - udl
          - pks
          - pkb
          - pls
          - trg
