package registry

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// BuildKitConfigGenerator generates BuildKit configuration files that route
// image pulls through the local Zot registry mirror. This enables on-demand
// caching of base images from Docker Hub, GHCR, etc.
type BuildKitConfigGenerator interface {
	// Generate creates a buildkitd.toml file with Zot as a mirror for configured
	// upstream registries. Returns the path to the generated file.
	Generate(endpoint string, mirrors []MirrorConfig, outputDir string) (string, error)
}

// DefaultBuildKitConfigGenerator implements BuildKitConfigGenerator.
type DefaultBuildKitConfigGenerator struct{}

// NewBuildKitConfigGenerator creates a new DefaultBuildKitConfigGenerator.
func NewBuildKitConfigGenerator() *DefaultBuildKitConfigGenerator {
	return &DefaultBuildKitConfigGenerator{}
}

// Generate creates a buildkitd.toml that configures Zot as a pull-through
// mirror for all configured upstream registries. The generated file is written
// to outputDir/buildkitd.toml and the path is returned.
//
// The endpoint should be host:port (e.g., "localhost:5001").
// Mirrors come from defaultMirrors() — the single source of truth.
func (g *DefaultBuildKitConfigGenerator) Generate(endpoint string, mirrors []MirrorConfig, outputDir string) (string, error) {
	if endpoint == "" {
		return "", fmt.Errorf("endpoint is required")
	}
	if len(mirrors) == 0 {
		return "", fmt.Errorf("at least one mirror is required")
	}

	if err := os.MkdirAll(outputDir, 0700); err != nil {
		return "", fmt.Errorf("failed to create output directory: %w", err)
	}

	content := generateBuildKitTOML(endpoint, mirrors)
	outputPath := filepath.Join(outputDir, "buildkitd.toml")

	if err := os.WriteFile(outputPath, []byte(content), configFileMode); err != nil {
		return "", fmt.Errorf("failed to write buildkitd.toml: %w", err)
	}

	return outputPath, nil
}

// generateBuildKitTOML builds the TOML content string for buildkitd.toml.
// Each mirror prefix (e.g., "docker.io") gets a registry section with the
// Zot endpoint configured as an HTTP mirror.
func generateBuildKitTOML(endpoint string, mirrors []MirrorConfig) string {
	var b strings.Builder
	b.WriteString("# Generated by dvm — do not edit manually\n")
	b.WriteString("# Routes image pulls through local Zot registry cache\n\n")

	for _, mirror := range mirrors {
		if mirror.Prefix == "" {
			continue
		}
		fmt.Fprintf(&b, "[registry.\"%s\"]\n", mirror.Prefix)
		fmt.Fprintf(&b, "  mirrors = [\"%s\"]\n", endpoint)
		fmt.Fprintf(&b, "[registry.\"%s\".mirror.\"%s\"]\n", mirror.Prefix, endpoint)
		b.WriteString("  http = true\n\n")
	}

	return b.String()
}

// EndpointFromURL extracts a host:port string from a full URL endpoint.
// For example, "http://localhost:5001" becomes "localhost:5001".
func EndpointFromURL(urlStr string) string {
	s := urlStr
	s = strings.TrimPrefix(s, "http://")
	s = strings.TrimPrefix(s, "https://")
	s = strings.TrimSuffix(s, "/")
	return s
}

// EndpointForVM rewrites a registry URL so it is reachable from inside a
// Colima/Docker VM. BuildKit and containerd run inside the VM where
// "localhost" refers to the VM itself, not the macOS host. We replace
// localhost/127.0.0.1 with host.docker.internal which Colima resolves to
// the host gateway IP (e.g. 192.168.5.2). See issue #386.
func EndpointForVM(endpoint string) string {
	endpoint = strings.Replace(endpoint, "localhost", "host.docker.internal", 1)
	endpoint = strings.Replace(endpoint, "127.0.0.1", "host.docker.internal", 1)
	return endpoint
}
