package registry

import (
	"fmt"
	"os"
	"time"

	"github.com/rmkohlman/MaestroSDK/paths"
)

// GoModuleConfig holds configuration for the Athens Go module proxy.
type GoModuleConfig struct {
	// Enabled determines if the proxy should be used
	Enabled bool `yaml:"enabled"`

	// Lifecycle determines when the proxy runs: "persistent", "on-demand", or "manual"
	Lifecycle string `yaml:"lifecycle"`

	// Port is the port the proxy listens on
	Port int `yaml:"port"`

	// Storage is the directory where cached modules are stored
	Storage string `yaml:"storage"`

	// IdleTimeout is how long to wait before shutting down an idle proxy (on-demand mode)
	IdleTimeout time.Duration `yaml:"idleTimeout"`

	// Upstreams are the upstream Go module proxies to use
	Upstreams []UpstreamProxyConfig `yaml:"upstreams"`
}

// UpstreamProxyConfig configures an upstream Go module proxy.
type UpstreamProxyConfig struct {
	// Name is a friendly name for this proxy
	Name string `yaml:"name"`

	// URL is the upstream proxy URL (e.g., "https://proxy.golang.org")
	URL string `yaml:"url"`
}

// Validate checks if the Go module proxy configuration is valid.
func (c *GoModuleConfig) Validate() error {
	// Port must be in valid range and not a reserved/privileged port
	if c.Port < 1024 || c.Port > 65535 {
		return ErrInvalidConfig
	}
	if c.Storage == "" {
		return ErrInvalidConfig
	}
	if c.Lifecycle != "" && c.Lifecycle != "persistent" && c.Lifecycle != "on-demand" && c.Lifecycle != "manual" {
		return ErrInvalidConfig
	}

	// Validate upstream URLs
	for _, upstream := range c.Upstreams {
		if err := upstream.Validate(); err != nil {
			return err
		}
	}

	return nil
}

// Validate checks if the upstream proxy configuration is valid.
func (u *UpstreamProxyConfig) Validate() error {
	if u.URL == "" {
		return ErrInvalidConfig
	}
	// Simple URL validation - check for http:// or https://
	if len(u.URL) < 8 || (u.URL[:7] != "http://" && u.URL[:8] != "https://") {
		return ErrInvalidConfig
	}
	return nil
}

// GenerateAthensConfig generates an Athens proxy configuration TOML from a GoModuleConfig.
func GenerateAthensConfig(cfg GoModuleConfig) (string, error) {
	// Validate config first
	if err := cfg.Validate(); err != nil {
		return "", fmt.Errorf("invalid configuration: %w", err)
	}

	// Use default upstreams if none specified
	upstreams := cfg.Upstreams
	if len(upstreams) == 0 {
		upstreams = defaultUpstreams()
	}

	// Build GOPROXY value from upstreams
	goproxy := ""
	for i, upstream := range upstreams {
		if i > 0 {
			goproxy += ","
		}
		goproxy += upstream.URL
	}
	// Add direct fallback
	goproxy += ",direct"

	// Build Athens config in TOML format
	// Athens config reference: https://docs.gomods.io/configuration/
	config := fmt.Sprintf(`# Athens Configuration
# Generated by DevOpsMaestro

# Port to listen on
Port = "127.0.0.1:%d"

# Storage configuration
[Storage]
Type = "disk"

[Storage.Disk]
RootPath = "%s"

# Go environment
[GoEnv]
GOPROXY = "%s"
`, cfg.Port, cfg.Storage, goproxy)

	return config, nil
}

// DefaultGoModuleConfig returns a GoModuleConfig with sensible defaults.
func DefaultGoModuleConfig() GoModuleConfig {
	homeDir, _ := os.UserHomeDir()
	return GoModuleConfig{
		Enabled:     true,
		Lifecycle:   "on-demand",
		Port:        3000,
		Storage:     paths.New(homeDir).AthensStorage(),
		IdleTimeout: 30 * time.Minute,
		Upstreams:   defaultUpstreams(),
	}
}

// defaultUpstreams returns the default set of upstream Go module proxies.
func defaultUpstreams() []UpstreamProxyConfig {
	return []UpstreamProxyConfig{
		{
			Name: "proxy.golang.org",
			URL:  "https://proxy.golang.org",
		},
	}
}
