package registry

import (
	"fmt"
	"path/filepath"
	"time"

	"github.com/rmkohlman/MaestroSDK/paths"
)

// PyPIProxyConfig holds configuration for the devpi PyPI proxy.
type PyPIProxyConfig struct {
	// Enabled determines if the proxy should be used
	Enabled bool `yaml:"enabled"`

	// Lifecycle determines when the proxy runs: "persistent", "on-demand", or "manual"
	Lifecycle string `yaml:"lifecycle"`

	// Port is the port the proxy listens on
	Port int `yaml:"port"`

	// Storage is the directory where proxy data is stored
	Storage string `yaml:"storage"`

	// ServerDir is the directory for devpi server data (optional, defaults to Storage/server)
	ServerDir string `yaml:"serverDir"`

	// IdleTimeout is how long to wait before shutting down an idle proxy (on-demand mode)
	IdleTimeout time.Duration `yaml:"idleTimeout"`

	// Upstreams are the upstream PyPI indexes to use
	Upstreams []PyPIUpstreamConfig `yaml:"upstreams"`
}

// PyPIUpstreamConfig configures an upstream PyPI index.
type PyPIUpstreamConfig struct {
	// Name is a friendly name for this index
	Name string `yaml:"name"`

	// URL is the upstream index URL (e.g., "https://pypi.org/simple")
	URL string `yaml:"url"`
}

// PyPIProxyStatus represents the current state of the PyPI proxy.
type PyPIProxyStatus struct {
	// State is "running" or "stopped"
	State string

	// PID is the process ID (0 if stopped)
	PID int

	// Port is the configured port
	Port int

	// Storage is the storage directory path
	Storage string

	// Version is the devpi-server version
	Version string

	// Uptime is how long the proxy has been running
	Uptime time.Duration

	// PackageCount is the number of packages cached
	PackageCount int

	// DiskUsage is the total disk space used (bytes)
	DiskUsage int64
}

// Validate checks if the PyPI proxy configuration is valid.
func (c *PyPIProxyConfig) Validate() error {
	// Port must be in valid range and not a reserved/privileged port
	if c.Port < 1024 || c.Port > 65535 {
		return ErrInvalidConfig
	}
	if c.Storage == "" {
		return ErrInvalidConfig
	}
	if c.Lifecycle != "persistent" && c.Lifecycle != "on-demand" && c.Lifecycle != "manual" {
		return ErrInvalidConfig
	}

	// Validate upstream URLs
	for _, upstream := range c.Upstreams {
		if err := upstream.Validate(); err != nil {
			return err
		}
	}

	return nil
}

// Validate checks if the upstream index configuration is valid.
func (u *PyPIUpstreamConfig) Validate() error {
	if u.URL == "" {
		return ErrInvalidConfig
	}
	// Simple URL validation - check for http:// or https://
	if len(u.URL) < 8 || (u.URL[:7] != "http://" && u.URL[:8] != "https://") {
		return ErrInvalidConfig
	}
	return nil
}

// GenerateDevpiConfig generates a devpi proxy configuration from a PyPIProxyConfig.
// Returns configuration as a string (command-line args format, not TOML/JSON).
func GenerateDevpiConfig(cfg PyPIProxyConfig) (string, error) {
	// Validate config first
	if err := cfg.Validate(); err != nil {
		return "", fmt.Errorf("invalid configuration: %w", err)
	}

	// Use default upstreams if none specified
	upstreams := cfg.Upstreams
	if len(upstreams) == 0 {
		upstreams = defaultPyPIUpstreams()
	}

	// Determine server directory
	serverDir := cfg.ServerDir
	if serverDir == "" {
		serverDir = filepath.Join(cfg.Storage, "server")
	}

	// Build devpi command-line configuration
	// devpi-server primarily uses command-line args
	config := fmt.Sprintf(`# Devpi Server Configuration
# Generated by DevOpsMaestro

# Server directory (for devpi-init and devpi-server)
serverdir: %s

# Port to listen on
port: %d

# Host to bind to (localhost for security)
host: 127.0.0.1

# Upstream indexes
`, serverDir, cfg.Port)

	// Add upstream configurations
	for _, upstream := range upstreams {
		config += fmt.Sprintf("# Upstream: %s (%s)\n", upstream.Name, upstream.URL)
	}

	return config, nil
}

// DefaultPyPIProxyConfig returns a PyPIProxyConfig with sensible defaults.
func DefaultPyPIProxyConfig() PyPIProxyConfig {
	var storage string
	if pc, err := paths.Default(); err == nil {
		storage = pc.DevpiStorage()
	}
	return PyPIProxyConfig{
		Enabled:     true,
		Lifecycle:   "on-demand",
		Port:        3141,
		Storage:     storage,
		IdleTimeout: 30 * time.Minute,
		Upstreams:   defaultPyPIUpstreams(),
	}
}

// defaultPyPIUpstreams returns the default set of upstream PyPI indexes.
func defaultPyPIUpstreams() []PyPIUpstreamConfig {
	return []PyPIUpstreamConfig{
		{
			Name: "pypi",
			URL:  "https://pypi.org/simple",
		},
	}
}
