package registry

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ContainerdConfigGenerator generates containerd hosts.toml configuration files
// that route nerdctl/containerd image pulls through the local Zot registry mirror.
type ContainerdConfigGenerator interface {
	// Generate creates hosts.toml files for each configured upstream registry.
	// Returns the path to the certs.d directory containing the generated files.
	Generate(endpoint string, mirrors []MirrorConfig, outputDir string) (string, error)
}

// DefaultContainerdConfigGenerator implements ContainerdConfigGenerator.
type DefaultContainerdConfigGenerator struct{}

// NewContainerdConfigGenerator creates a new DefaultContainerdConfigGenerator.
func NewContainerdConfigGenerator() *DefaultContainerdConfigGenerator {
	return &DefaultContainerdConfigGenerator{}
}

// Generate creates containerd hosts.toml files for each mirror prefix.
// For example, for the "docker.io" mirror it writes:
//
//	outputDir/certs.d/docker.io/hosts.toml
//
// Each file configures Zot as a pull-through mirror with HTTP access.
// Returns the certs.d directory path.
func (g *DefaultContainerdConfigGenerator) Generate(endpoint string, mirrors []MirrorConfig, outputDir string) (string, error) {
	if endpoint == "" {
		return "", fmt.Errorf("endpoint is required")
	}
	if len(mirrors) == 0 {
		return "", fmt.Errorf("at least one mirror is required")
	}

	certsDir := filepath.Join(outputDir, "certs.d")

	for _, mirror := range mirrors {
		if mirror.Prefix == "" {
			continue
		}
		if err := writeContainerdHostsTOML(certsDir, endpoint, mirror); err != nil {
			return "", fmt.Errorf("failed to write hosts.toml for %s: %w", mirror.Prefix, err)
		}
	}

	return certsDir, nil
}

// writeContainerdHostsTOML writes a single hosts.toml file for one mirror.
func writeContainerdHostsTOML(certsDir, endpoint string, mirror MirrorConfig) error {
	registryDir := filepath.Join(certsDir, mirror.Prefix)
	if err := os.MkdirAll(registryDir, 0700); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	content := generateContainerdHostsTOML(endpoint, mirror)
	hostsPath := filepath.Join(registryDir, "hosts.toml")

	return os.WriteFile(hostsPath, []byte(content), configFileMode)
}

// generateContainerdHostsTOML builds the TOML content for a hosts.toml file.
func generateContainerdHostsTOML(endpoint string, mirror MirrorConfig) string {
	var b strings.Builder
	b.WriteString("# Generated by dvm — do not edit manually\n")
	fmt.Fprintf(&b, "# Routes %s pulls through local Zot registry cache\n\n", mirror.Prefix)
	fmt.Fprintf(&b, "server = \"%s\"\n\n", mirror.URL)
	fmt.Fprintf(&b, "[host.\"http://%s\"]\n", endpoint)
	b.WriteString("  capabilities = [\"pull\", \"resolve\"]\n")
	b.WriteString("  skip_verify = true\n")

	return b.String()
}
