package theme

import (
	"fmt"
	"sort"
	"strings"
)

// Generator generates Lua code for themes.
type Generator struct{}

// NewGenerator creates a new theme Lua generator.
func NewGenerator() *Generator {
	return &Generator{}
}

// GeneratedTheme contains all generated Lua files for a theme.
type GeneratedTheme struct {
	// PaletteLua is the palette module (theme/palette.lua)
	PaletteLua string
	// InitLua is the theme setup (theme/init.lua)
	InitLua string
	// PluginLua is the lazy.nvim plugin spec (plugins/colorscheme.lua)
	PluginLua string
	// ColorschemeLua is the standalone colorscheme implementation (theme/colorscheme.lua)
	// Only populated for standalone themes
	ColorschemeLua string
}

// Generate generates all Lua files for a theme.
func (g *Generator) Generate(t *Theme) (*GeneratedTheme, error) {
	if err := t.Validate(); err != nil {
		return nil, err
	}

	palette, err := g.generatePalette(t)
	if err != nil {
		return nil, err
	}

	initLua, err := g.generateInit(t)
	if err != nil {
		return nil, err
	}

	pluginLua, err := g.generatePlugin(t)
	if err != nil {
		return nil, err
	}

	result := &GeneratedTheme{
		PaletteLua: palette,
		InitLua:    initLua,
		PluginLua:  pluginLua,
	}

	// Generate standalone colorscheme code if this is a standalone theme
	if t.IsStandalone() {
		colorschemeLua, err := g.generateStandaloneColorscheme(t)
		if err != nil {
			return nil, err
		}
		result.ColorschemeLua = colorschemeLua
	}

	return result, nil
}

// generatePalette generates the palette module that other plugins can require.
// Usage in other plugins: local palette = require("theme").palette
func (g *Generator) generatePalette(t *Theme) (string, error) {
	var sb strings.Builder

	sb.WriteString("-- Theme Palette: " + t.Name + "\n")
	sb.WriteString("-- This module exports theme colors for use by other plugins.\n")
	sb.WriteString("-- Usage: local palette = require(\"theme\").palette\n")
	sb.WriteString("-- Generated by nvp (NvimOps)\n\n")

	sb.WriteString("local M = {}\n\n")

	// Theme metadata
	sb.WriteString("-- Theme metadata\n")
	sb.WriteString(fmt.Sprintf("M.name = %q\n", t.Name))
	if t.Style != "" {
		sb.WriteString(fmt.Sprintf("M.style = %q\n", t.Style))
	}
	sb.WriteString(fmt.Sprintf("M.transparent = %s\n", boolToLua(t.Transparent)))
	sb.WriteString("\n")

	// Colors palette
	sb.WriteString("-- Color palette\n")
	sb.WriteString("M.colors = {\n")

	// Sort keys for consistent output
	keys := make([]string, 0, len(t.Colors))
	for k := range t.Colors {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		sb.WriteString(fmt.Sprintf("  %s = %q,\n", key, t.Colors[key]))
	}
	sb.WriteString("}\n\n")

	// Semantic color aliases (common names that plugins expect)
	sb.WriteString("-- Semantic aliases for common plugin usage\n")
	sb.WriteString("M.semantic = {\n")
	g.writeSemanticAliases(&sb, t)
	sb.WriteString("}\n\n")

	// Helper function to get color with fallback
	sb.WriteString("-- Get a color with optional fallback\n")
	sb.WriteString("function M.get(name, fallback)\n")
	sb.WriteString("  return M.colors[name] or M.semantic[name] or fallback\n")
	sb.WriteString("end\n\n")

	// Helper to check if transparent mode
	sb.WriteString("-- Check if transparent mode is enabled\n")
	sb.WriteString("function M.is_transparent()\n")
	sb.WriteString("  return M.transparent\n")
	sb.WriteString("end\n\n")

	sb.WriteString("return M\n")

	return sb.String(), nil
}

// writeSemanticAliases maps theme colors to common semantic names
func (g *Generator) writeSemanticAliases(sb *strings.Builder, t *Theme) {
	// Map common color names to semantic meanings
	semanticMap := map[string][]string{
		"background":  {"bg", "bg_dark"},
		"foreground":  {"fg", "fg_dark"},
		"selection":   {"bg_visual", "bg_highlight"},
		"comment":     {"comment", "fg_gutter"},
		"border":      {"border", "fg_gutter"},
		"cursor_line": {"bg_highlight", "bg_visual"},
		"search":      {"bg_search", "bg_highlight"},
		"popup":       {"bg_popup", "bg_float", "bg_dark"},
		"sidebar":     {"bg_sidebar", "bg_dark"},
		"statusline":  {"bg_statusline", "bg_dark"},
		"error":       {"error", "red"},
		"warning":     {"warning", "yellow", "orange"},
		"info":        {"info", "blue", "cyan"},
		"hint":        {"hint", "cyan", "teal"},
		"success":     {"success", "green"},
		"added":       {"added", "git_add", "green"},
		"modified":    {"modified", "git_change", "blue", "yellow"},
		"removed":     {"removed", "git_delete", "red"},
	}

	for semantic, candidates := range semanticMap {
		for _, candidate := range candidates {
			if color, ok := t.Colors[candidate]; ok {
				sb.WriteString(fmt.Sprintf("  %s = %q,\n", semantic, color))
				break
			}
		}
	}
}

// generateInit generates the theme init module.
func (g *Generator) generateInit(t *Theme) (string, error) {
	var sb strings.Builder

	sb.WriteString("-- Theme: " + t.Name + "\n")
	if t.Description != "" {
		sb.WriteString("-- " + t.Description + "\n")
	}
	sb.WriteString("-- Generated by nvp (NvimOps)\n\n")

	sb.WriteString("local M = {}\n\n")

	// Re-export palette
	sb.WriteString("-- Re-export palette for easy access\n")
	sb.WriteString("M.palette = require(\"theme.palette\")\n\n")

	// Setup function that plugins can call
	sb.WriteString("-- Setup function (called automatically by colorscheme plugin)\n")
	sb.WriteString("function M.setup()\n")
	sb.WriteString("  -- Theme is configured via the colorscheme plugin\n")
	sb.WriteString("  -- This function is for any additional setup if needed\n")
	sb.WriteString("end\n\n")

	// Helper to apply highlights using palette
	sb.WriteString("-- Apply a highlight group using palette colors\n")
	sb.WriteString("function M.highlight(group, opts)\n")
	sb.WriteString("  local hl = {}\n")
	sb.WriteString("  if opts.fg then hl.fg = M.palette.get(opts.fg, opts.fg) end\n")
	sb.WriteString("  if opts.bg then hl.bg = M.palette.get(opts.bg, opts.bg) end\n")
	sb.WriteString("  if opts.sp then hl.sp = M.palette.get(opts.sp, opts.sp) end\n")
	sb.WriteString("  if opts.bold then hl.bold = true end\n")
	sb.WriteString("  if opts.italic then hl.italic = true end\n")
	sb.WriteString("  if opts.underline then hl.underline = true end\n")
	sb.WriteString("  if opts.undercurl then hl.undercurl = true end\n")
	sb.WriteString("  vim.api.nvim_set_hl(0, group, hl)\n")
	sb.WriteString("end\n\n")

	// Lualine theme generator
	sb.WriteString("-- Generate lualine theme from palette\n")
	sb.WriteString("function M.lualine_theme()\n")
	sb.WriteString("  local p = M.palette\n")
	sb.WriteString("  return {\n")
	sb.WriteString("    normal = {\n")
	sb.WriteString("      a = { bg = p.get(\"blue\", p.get(\"fg\")), fg = p.get(\"bg\"), gui = \"bold\" },\n")
	sb.WriteString("      b = { bg = p.get(\"bg_highlight\", p.get(\"bg\")), fg = p.get(\"fg\") },\n")
	sb.WriteString("      c = { bg = p.get(\"bg_statusline\", p.get(\"bg\")), fg = p.get(\"fg_dark\", p.get(\"fg\")) },\n")
	sb.WriteString("    },\n")
	sb.WriteString("    insert = {\n")
	sb.WriteString("      a = { bg = p.get(\"green\", p.get(\"fg\")), fg = p.get(\"bg\"), gui = \"bold\" },\n")
	sb.WriteString("    },\n")
	sb.WriteString("    visual = {\n")
	sb.WriteString("      a = { bg = p.get(\"purple\", p.get(\"magenta\", p.get(\"fg\"))), fg = p.get(\"bg\"), gui = \"bold\" },\n")
	sb.WriteString("    },\n")
	sb.WriteString("    replace = {\n")
	sb.WriteString("      a = { bg = p.get(\"red\", p.get(\"fg\")), fg = p.get(\"bg\"), gui = \"bold\" },\n")
	sb.WriteString("    },\n")
	sb.WriteString("    command = {\n")
	sb.WriteString("      a = { bg = p.get(\"yellow\", p.get(\"orange\", p.get(\"fg\"))), fg = p.get(\"bg\"), gui = \"bold\" },\n")
	sb.WriteString("    },\n")
	sb.WriteString("    inactive = {\n")
	sb.WriteString("      a = { bg = p.get(\"bg_statusline\", p.get(\"bg\")), fg = p.get(\"fg_gutter\", p.get(\"fg\")) },\n")
	sb.WriteString("      b = { bg = p.get(\"bg_statusline\", p.get(\"bg\")), fg = p.get(\"fg_gutter\", p.get(\"fg\")) },\n")
	sb.WriteString("      c = { bg = p.get(\"bg_statusline\", p.get(\"bg\")), fg = p.get(\"fg_gutter\", p.get(\"fg\")) },\n")
	sb.WriteString("    },\n")
	sb.WriteString("  }\n")
	sb.WriteString("end\n\n")

	// Bufferline highlights generator
	sb.WriteString("-- Generate bufferline highlights from palette\n")
	sb.WriteString("function M.bufferline_highlights()\n")
	sb.WriteString("  local p = M.palette\n")
	sb.WriteString("  return {\n")
	sb.WriteString("    fill = { bg = p.get(\"bg_dark\", p.get(\"bg\")) },\n")
	sb.WriteString("    background = { bg = p.get(\"bg_dark\", p.get(\"bg\")), fg = p.get(\"fg_gutter\", p.get(\"fg\")) },\n")
	sb.WriteString("    buffer_selected = { bg = p.get(\"bg\"), fg = p.get(\"fg\"), bold = true },\n")
	sb.WriteString("    separator = { bg = p.get(\"bg_dark\", p.get(\"bg\")), fg = p.get(\"bg_dark\", p.get(\"bg\")) },\n")
	sb.WriteString("    separator_selected = { bg = p.get(\"bg\"), fg = p.get(\"bg_dark\", p.get(\"bg\")) },\n")
	sb.WriteString("  }\n")
	sb.WriteString("end\n\n")

	// Telescope border color
	sb.WriteString("-- Get telescope border color\n")
	sb.WriteString("function M.telescope_border()\n")
	sb.WriteString("  return M.palette.get(\"border\", M.palette.get(\"fg_gutter\"))\n")
	sb.WriteString("end\n\n")

	sb.WriteString("return M\n")

	return sb.String(), nil
}

// generatePlugin generates the lazy.nvim plugin spec for the colorscheme.
func (g *Generator) generatePlugin(t *Theme) (string, error) {
	// For standalone themes, generate a different plugin spec
	if t.IsStandalone() {
		return g.generateStandalonePlugin(t)
	}

	var sb strings.Builder

	sb.WriteString("-- Colorscheme: " + t.Name + "\n")
	if t.Description != "" {
		sb.WriteString("-- " + t.Description + "\n")
	}
	sb.WriteString("-- Generated by nvp (NvimOps)\n\n")

	sb.WriteString("return {\n")
	sb.WriteString(fmt.Sprintf("  %q,\n", t.Plugin.Repo))
	sb.WriteString("  priority = 1000,\n")
	sb.WriteString("  lazy = false,\n")

	if t.Plugin.Branch != "" {
		sb.WriteString(fmt.Sprintf("  branch = %q,\n", t.Plugin.Branch))
	}
	if t.Plugin.Tag != "" {
		sb.WriteString(fmt.Sprintf("  tag = %q,\n", t.Plugin.Tag))
	}

	sb.WriteString("  config = function()\n")
	sb.WriteString("    -- Load palette for reference\n")
	sb.WriteString("    local palette = require(\"theme.palette\")\n\n")

	// Generate setup based on theme plugin
	g.generateSetup(&sb, t)

	// Set colorscheme
	colorscheme := t.GetColorschemeCommand()
	sb.WriteString(fmt.Sprintf("    vim.cmd.colorscheme(%q)\n", colorscheme))

	sb.WriteString("  end,\n")
	sb.WriteString("}\n")

	return sb.String(), nil
}

// boolToLua converts a bool to Lua boolean string
func boolToLua(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

// toLuaValue converts a Go value to Lua representation
func toLuaValue(v any) string {
	switch val := v.(type) {
	case bool:
		return boolToLua(val)
	case string:
		return fmt.Sprintf("%q", val)
	case int, int64, float64:
		return fmt.Sprintf("%v", val)
	case map[string]any:
		var sb strings.Builder
		sb.WriteString("{\n")
		for k, v := range val {
			sb.WriteString(fmt.Sprintf("        %s = %s,\n", k, toLuaValue(v)))
		}
		sb.WriteString("      }")
		return sb.String()
	default:
		return fmt.Sprintf("%v", val)
	}
}
