package theme

import (
	"fmt"
	"strings"
)

// =============================================================================
// Standalone Theme Generation
// =============================================================================

// generateStandalonePlugin generates a lazy.nvim plugin spec for standalone themes.
// This creates a plugin that loads from the local theme directory instead of a repo.
func (g *Generator) generateStandalonePlugin(t *Theme) (string, error) {
	var sb strings.Builder

	sb.WriteString("-- Standalone Colorscheme: " + t.Name + "\n")
	if t.Description != "" {
		sb.WriteString("-- " + t.Description + "\n")
	}
	sb.WriteString("-- Self-contained theme - no external plugin required\n")
	sb.WriteString("-- Generated by nvp (NvimOps)\n\n")

	sb.WriteString("return {\n")
	sb.WriteString("  dir = vim.fn.stdpath(\"config\") .. \"/lua/theme\",\n")
	sb.WriteString(fmt.Sprintf("  name = %q,\n", t.Name))
	sb.WriteString("  priority = 1000,\n")
	sb.WriteString("  lazy = false,\n")
	sb.WriteString("  config = function()\n")
	sb.WriteString("    require(\"theme.colorscheme\").setup()\n")
	sb.WriteString("  end,\n")
	sb.WriteString("}\n")

	return sb.String(), nil
}

// generateStandaloneColorscheme generates a self-contained colorscheme implementation.
// This creates a colorscheme that applies highlights directly via vim.api.nvim_set_hl().
func (g *Generator) generateStandaloneColorscheme(t *Theme) (string, error) {
	var sb strings.Builder

	sb.WriteString("-- Colorscheme: " + t.Name + "\n")
	if t.Description != "" {
		sb.WriteString("-- " + t.Description + "\n")
	}
	sb.WriteString("-- Self-contained parametric theme\n")
	sb.WriteString("-- Generated by nvp (NvimOps)\n\n")

	sb.WriteString("local M = {}\n\n")

	sb.WriteString("function M.setup(opts)\n")
	sb.WriteString("  opts = opts or {}\n")
	sb.WriteString("  local palette = require(\"theme.palette\")\n")
	sb.WriteString("  local colors = palette.colors\n\n")

	sb.WriteString("  -- Clear existing highlights\n")
	sb.WriteString("  vim.cmd(\"hi clear\")\n")
	sb.WriteString("  if vim.fn.exists(\"syntax_on\") then\n")
	sb.WriteString("    vim.cmd(\"syntax reset\")\n")
	sb.WriteString("  end\n\n")

	sb.WriteString("  -- Set colorscheme name\n")
	sb.WriteString(fmt.Sprintf("  vim.g.colors_name = %q\n\n", t.Name))

	sb.WriteString("  -- Helper function to apply highlights\n")
	sb.WriteString("  local hl = function(name, val)\n")
	sb.WriteString("    vim.api.nvim_set_hl(0, name, val)\n")
	sb.WriteString("  end\n\n")

	// Generate highlight groups
	g.generateStandaloneHighlights(&sb, t)

	sb.WriteString("end\n\n")

	sb.WriteString("-- Auto-setup on load\n")
	sb.WriteString("M.setup()\n\n")

	sb.WriteString("return M\n")

	return sb.String(), nil
}

// generateStandaloneHighlights generates all highlight groups for a standalone theme.
func (g *Generator) generateStandaloneHighlights(sb *strings.Builder, t *Theme) {
	// UI highlight groups
	sb.WriteString("  -- UI Groups\n")
	g.writeHighlight(sb, "Normal", map[string]string{"fg": "fg", "bg": "bg"}, t.Transparent)
	g.writeHighlight(sb, "NormalFloat", map[string]string{"fg": "fg", "bg": "bg_dark"}, t.Transparent)
	g.writeHighlight(sb, "NormalNC", map[string]string{"fg": "fg_dark", "bg": "bg"}, t.Transparent)
	g.writeHighlight(sb, "CursorLine", map[string]string{"bg": "bg_highlight"}, false)
	g.writeHighlight(sb, "CursorColumn", map[string]string{"bg": "bg_highlight"}, false)
	g.writeHighlight(sb, "Visual", map[string]string{"bg": "bg_visual"}, false)
	g.writeHighlight(sb, "Search", map[string]string{"fg": "bg", "bg": "bg_search"}, false)
	g.writeHighlight(sb, "IncSearch", map[string]string{"fg": "bg", "bg": "orange"}, false)

	// Status line
	g.writeHighlight(sb, "StatusLine", map[string]string{"fg": "fg", "bg": "bg_statusline"}, t.Transparent)
	g.writeHighlight(sb, "StatusLineNC", map[string]string{"fg": "fg_gutter", "bg": "bg_statusline"}, t.Transparent)

	// Tab line
	g.writeHighlight(sb, "TabLine", map[string]string{"fg": "fg_gutter", "bg": "bg_statusline"}, t.Transparent)
	g.writeHighlight(sb, "TabLineFill", map[string]string{"bg": "bg_dark"}, t.Transparent)
	g.writeHighlight(sb, "TabLineSel", map[string]string{"fg": "fg", "bg": "bg"}, false)

	// Popup menu
	g.writeHighlight(sb, "Pmenu", map[string]string{"fg": "fg", "bg": "bg_popup"}, t.Transparent)
	g.writeHighlight(sb, "PmenuSel", map[string]string{"fg": "bg", "bg": "blue"}, false)
	g.writeHighlight(sb, "PmenuSbar", map[string]string{"bg": "bg_highlight"}, t.Transparent)
	g.writeHighlight(sb, "PmenuThumb", map[string]string{"bg": "fg_gutter"}, false)

	// Line numbers and signs
	g.writeHighlight(sb, "LineNr", map[string]string{"fg": "fg_gutter"}, false)
	g.writeHighlight(sb, "CursorLineNr", map[string]string{"fg": "orange", "bold": "true"}, false)
	g.writeHighlight(sb, "SignColumn", map[string]string{"fg": "fg_gutter", "bg": "bg"}, t.Transparent)
	g.writeHighlight(sb, "VertSplit", map[string]string{"fg": "border"}, false)
	g.writeHighlight(sb, "WinSeparator", map[string]string{"fg": "border"}, false)

	sb.WriteString("\n  -- Syntax Groups\n")

	// Comments
	g.writeHighlight(sb, "Comment", map[string]string{"fg": "comment", "italic": "true"}, false)
	g.writeHighlight(sb, "NonText", map[string]string{"fg": "fg_gutter"}, false)
	g.writeHighlight(sb, "SpecialKey", map[string]string{"fg": "fg_gutter"}, false)

	// Constants and literals
	g.writeHighlight(sb, "String", map[string]string{"fg": "green"}, false)
	g.writeHighlight(sb, "Number", map[string]string{"fg": "orange"}, false)
	g.writeHighlight(sb, "Boolean", map[string]string{"fg": "orange"}, false)
	g.writeHighlight(sb, "Float", map[string]string{"fg": "orange"}, false)
	g.writeHighlight(sb, "Character", map[string]string{"fg": "green"}, false)
	g.writeHighlight(sb, "Constant", map[string]string{"fg": "orange"}, false)

	// Identifiers and functions
	g.writeHighlight(sb, "Identifier", map[string]string{"fg": "red"}, false)
	g.writeHighlight(sb, "Function", map[string]string{"fg": "blue", "bold": "true"}, false)

	// Statements and keywords
	g.writeHighlight(sb, "Statement", map[string]string{"fg": "purple", "bold": "true"}, false)
	g.writeHighlight(sb, "Keyword", map[string]string{"fg": "purple", "bold": "true"}, false)
	g.writeHighlight(sb, "Conditional", map[string]string{"fg": "purple", "bold": "true"}, false)
	g.writeHighlight(sb, "Repeat", map[string]string{"fg": "purple", "bold": "true"}, false)
	g.writeHighlight(sb, "Label", map[string]string{"fg": "purple"}, false)
	g.writeHighlight(sb, "Operator", map[string]string{"fg": "fg"}, false)
	g.writeHighlight(sb, "Exception", map[string]string{"fg": "red", "bold": "true"}, false)

	// Types and structures
	g.writeHighlight(sb, "Type", map[string]string{"fg": "cyan", "bold": "true"}, false)
	g.writeHighlight(sb, "Structure", map[string]string{"fg": "cyan"}, false)
	g.writeHighlight(sb, "StorageClass", map[string]string{"fg": "purple"}, false)
	g.writeHighlight(sb, "Typedef", map[string]string{"fg": "cyan"}, false)

	// Preprocessor
	g.writeHighlight(sb, "PreProc", map[string]string{"fg": "magenta"}, false)
	g.writeHighlight(sb, "Include", map[string]string{"fg": "magenta"}, false)
	g.writeHighlight(sb, "Define", map[string]string{"fg": "magenta"}, false)
	g.writeHighlight(sb, "Macro", map[string]string{"fg": "magenta"}, false)
	g.writeHighlight(sb, "PreCondit", map[string]string{"fg": "magenta"}, false)

	// Special
	g.writeHighlight(sb, "Special", map[string]string{"fg": "cyan"}, false)
	g.writeHighlight(sb, "SpecialChar", map[string]string{"fg": "cyan"}, false)
	g.writeHighlight(sb, "Tag", map[string]string{"fg": "red"}, false)
	g.writeHighlight(sb, "Delimiter", map[string]string{"fg": "fg"}, false)
	g.writeHighlight(sb, "Debug", map[string]string{"fg": "red"}, false)

	sb.WriteString("\n  -- Diagnostics\n")
	g.writeHighlight(sb, "DiagnosticError", map[string]string{"fg": "error"}, false)
	g.writeHighlight(sb, "DiagnosticWarn", map[string]string{"fg": "warning"}, false)
	g.writeHighlight(sb, "DiagnosticInfo", map[string]string{"fg": "info"}, false)
	g.writeHighlight(sb, "DiagnosticHint", map[string]string{"fg": "hint"}, false)

	// Underlines for diagnostics
	g.writeHighlight(sb, "DiagnosticUnderlineError", map[string]string{"sp": "error", "undercurl": "true"}, false)
	g.writeHighlight(sb, "DiagnosticUnderlineWarn", map[string]string{"sp": "warning", "undercurl": "true"}, false)
	g.writeHighlight(sb, "DiagnosticUnderlineInfo", map[string]string{"sp": "info", "undercurl": "true"}, false)
	g.writeHighlight(sb, "DiagnosticUnderlineHint", map[string]string{"sp": "hint", "undercurl": "true"}, false)

	sb.WriteString("\n  -- Git Signs (if using gitsigns.nvim)\n")
	g.writeHighlight(sb, "GitSignsAdd", map[string]string{"fg": "green"}, false)
	g.writeHighlight(sb, "GitSignsChange", map[string]string{"fg": "yellow"}, false)
	g.writeHighlight(sb, "GitSignsDelete", map[string]string{"fg": "red"}, false)

	sb.WriteString("\n  -- Treesitter highlights\n")
	g.writeHighlight(sb, "@comment", map[string]string{"link": "Comment"}, false)
	g.writeHighlight(sb, "@string", map[string]string{"link": "String"}, false)
	g.writeHighlight(sb, "@number", map[string]string{"link": "Number"}, false)
	g.writeHighlight(sb, "@boolean", map[string]string{"link": "Boolean"}, false)
	g.writeHighlight(sb, "@function", map[string]string{"link": "Function"}, false)
	g.writeHighlight(sb, "@keyword", map[string]string{"link": "Keyword"}, false)
	g.writeHighlight(sb, "@type", map[string]string{"link": "Type"}, false)
	g.writeHighlight(sb, "@variable", map[string]string{"link": "Identifier"}, false)
}

// writeHighlight writes a single highlight group definition.
func (g *Generator) writeHighlight(sb *strings.Builder, group string, attrs map[string]string, transparent bool) {
	sb.WriteString(fmt.Sprintf("  hl(%q, {", group))

	first := true
	for attr, colorKey := range attrs {
		if !first {
			sb.WriteString(", ")
		}
		first = false

		switch attr {
		case "bold", "italic", "underline", "undercurl":
			sb.WriteString(fmt.Sprintf(" %s = %s", attr, colorKey))
		case "link":
			sb.WriteString(fmt.Sprintf(" link = %q", colorKey))
		default:
			// Handle transparent backgrounds
			if transparent && attr == "bg" && (colorKey == "bg_statusline" || colorKey == "bg_sidebar" || colorKey == "bg_float" || colorKey == "bg_popup" || colorKey == "bg_dark") {
				sb.WriteString(fmt.Sprintf(" %s = palette.is_transparent() and \"NONE\" or colors.%s", attr, colorKey))
			} else {
				sb.WriteString(fmt.Sprintf(" %s = colors.%s", attr, colorKey))
			}
		}
	}

	sb.WriteString(" })\n")
}
