// Package db provides a decoupled database abstraction layer.
//
// Architecture:
//   - Driver interface: Low-level database connection and query execution
//   - DataStore interface: High-level application data operations
//   - Row/Rows interfaces: Abstract result scanning (no sql.Row dependencies)
//   - Factory functions: Create implementations based on configuration
//
// Supported Drivers:
//   - SQLite (default, file-based)
//   - PostgreSQL (production, server-based)
//   - DuckDB (planned, analytics-focused)
//
// Example usage:
//
//	driver, err := db.NewDriver(db.DriverConfig{
//	    Type: db.DriverSQLite,
//	    Path: "~/.devopsmaestro/devopsmaestro.db",
//	})
//	store := db.NewStore(driver)
//	projects, err := store.ListProjects()
package db

import (
	"context"
	"io/fs"
)

// DriverType identifies the database driver type
type DriverType string

const (
	// DriverSQLite - SQLite file-based database (default)
	DriverSQLite DriverType = "sqlite"

	// DriverPostgres - PostgreSQL server-based database
	DriverPostgres DriverType = "postgres"

	// DriverDuckDB - DuckDB analytics-focused database (future)
	DriverDuckDB DriverType = "duckdb"

	// DriverMemory - In-memory SQLite for testing
	DriverMemory DriverType = "memory"
)

// Row represents a single database row result.
// This abstracts away sql.Row to allow different implementations.
type Row interface {
	// Scan copies columns from the row into the provided destinations.
	// The number of values must match the number of columns in the row.
	Scan(dest ...interface{}) error
}

// Rows represents multiple database row results.
// This abstracts away sql.Rows to allow different implementations.
type Rows interface {
	// Next prepares the next row for scanning.
	// Returns true if there is a row, false if no more rows or an error occurred.
	Next() bool

	// Scan copies columns from the current row into the provided destinations.
	Scan(dest ...interface{}) error

	// Close releases any resources held by the Rows.
	Close() error

	// Err returns any error encountered during iteration.
	Err() error

	// Columns returns the column names.
	Columns() ([]string, error)
}

// Result represents the result of an Execute operation.
// This abstracts away sql.Result to allow different implementations.
type Result interface {
	// LastInsertId returns the integer generated by the database
	// in response to a command (typically an auto-increment primary key).
	LastInsertId() (int64, error)

	// RowsAffected returns the number of rows affected by an
	// update, insert, or delete operation.
	RowsAffected() (int64, error)
}

// Driver is the low-level interface for database operations.
// Implementations handle connection management and query execution
// for specific database systems.
type Driver interface {
	// Connection Lifecycle

	// Connect establishes the database connection.
	Connect() error

	// Close closes the database connection.
	Close() error

	// Ping verifies the database connection is alive.
	Ping() error

	// Query Execution

	// Execute runs a command that doesn't return rows (INSERT, UPDATE, DELETE).
	// Returns a Result for accessing last insert ID and rows affected.
	Execute(query string, args ...interface{}) (Result, error)

	// ExecuteContext runs a command with context support.
	ExecuteContext(ctx context.Context, query string, args ...interface{}) (Result, error)

	// QueryRow executes a query expected to return at most one row.
	QueryRow(query string, args ...interface{}) Row

	// QueryRowContext executes a query with context support.
	QueryRowContext(ctx context.Context, query string, args ...interface{}) Row

	// Query executes a query that returns multiple rows.
	Query(query string, args ...interface{}) (Rows, error)

	// QueryContext executes a query with context support.
	QueryContext(ctx context.Context, query string, args ...interface{}) (Rows, error)

	// Transaction Support

	// Begin starts a new transaction.
	Begin() (Transaction, error)

	// BeginContext starts a new transaction with context.
	BeginContext(ctx context.Context) (Transaction, error)

	// Metadata

	// Type returns the driver type.
	Type() DriverType

	// DSN returns the data source name (connection string).
	DSN() string

	// MigrationDSN returns the DSN formatted for golang-migrate.
	MigrationDSN() string
}

// Transaction represents a database transaction.
type Transaction interface {
	// Execute runs a command within the transaction.
	Execute(query string, args ...interface{}) (Result, error)

	// QueryRow executes a query expected to return at most one row.
	QueryRow(query string, args ...interface{}) Row

	// Query executes a query that returns multiple rows.
	Query(query string, args ...interface{}) (Rows, error)

	// Commit commits the transaction.
	Commit() error

	// Rollback aborts the transaction.
	Rollback() error
}

// Migrator handles database schema migrations.
type Migrator interface {
	// Up applies all pending migrations.
	Up() error

	// Down rolls back the last migration.
	Down() error

	// Version returns the current migration version.
	Version() (uint, bool, error)

	// Steps applies n migrations (positive=up, negative=down).
	Steps(n int) error

	// Close releases migration resources.
	Close() error
}

// MigratorFactory creates a Migrator for the given driver.
type MigratorFactory interface {
	// NewMigrator creates a migrator using embedded migration files.
	NewMigrator(driver Driver, migrationsFS fs.FS) (Migrator, error)
}

// HealthCheck provides database health monitoring.
type HealthCheck interface {
	// IsHealthy returns true if the database is responsive.
	IsHealthy() bool

	// Stats returns connection pool statistics.
	Stats() DriverStats
}

// DriverStats contains database connection statistics.
type DriverStats struct {
	// OpenConnections is the number of open connections.
	OpenConnections int

	// InUse is the number of connections currently in use.
	InUse int

	// Idle is the number of idle connections.
	Idle int

	// WaitCount is the total number of connections waited for.
	WaitCount int64

	// MaxOpenConnections is the maximum number of open connections.
	MaxOpenConnections int
}

// QueryBuilder abstracts SQL query construction for different dialects.
type QueryBuilder interface {
	// Placeholder returns the placeholder for the given parameter index.
	// SQLite uses ?, PostgreSQL uses $1, $2, etc.
	Placeholder(index int) string

	// Now returns the SQL function for current timestamp.
	// SQLite uses datetime('now'), PostgreSQL uses NOW().
	Now() string

	// Boolean returns the SQL representation of a boolean.
	// SQLite uses 0/1, PostgreSQL uses TRUE/FALSE.
	Boolean(value bool) string

	// UpsertSuffix returns the SQL suffix for upsert operations.
	// SQLite uses "ON CONFLICT ... DO UPDATE", PostgreSQL uses "ON CONFLICT ... DO UPDATE".
	UpsertSuffix(conflictColumns []string, updateColumns []string) string

	// LimitOffset returns the SQL clause for pagination.
	LimitOffset(limit, offset int) string

	// Dialect returns the SQL dialect name.
	Dialect() string
}
