package cmd

import (
	"github.com/spf13/cobra"
)

// completionCmd represents the completion command
// This is auto-generated by Cobra, but we'll add custom documentation
var completionEnhanceCmd = &cobra.Command{
	Use:   "install-completion [shell]",
	Short: "Install shell completion (helper command)",
	Long: `Install shell completion for dvm.

This is a convenience command that automatically installs completions
for your shell. Alternatively, you can use 'dvm completion <shell>'
to generate the completion script manually.

Supported shells: bash, zsh, fish, powershell

Examples:
  # Install for zsh (auto-detects location)
  dvm completion install-completion zsh

  # Install for bash
  dvm completion install-completion bash

  # Or use the standard Cobra commands:
  dvm completion zsh > $(brew --prefix)/share/zsh/site-functions/_dvm
  dvm completion bash > /usr/local/etc/bash_completion.d/dvm`,
	ValidArgs: []string{"bash", "zsh", "fish", "powershell"},
	Args:      cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		// This is a placeholder - actual implementation would install completions
		shell := args[0]
		cmd.Printf("To install %s completion, run:\n\n", shell)

		switch shell {
		case "bash":
			cmd.Println("  # Linux:")
			cmd.Println("  dvm completion bash > /etc/bash_completion.d/dvm")
			cmd.Println()
			cmd.Println("  # macOS:")
			cmd.Println("  dvm completion bash > $(brew --prefix)/etc/bash_completion.d/dvm")
		case "zsh":
			cmd.Println("  # macOS:")
			cmd.Println("  dvm completion zsh > $(brew --prefix)/share/zsh/site-functions/_dvm")
			cmd.Println()
			cmd.Println("  # Linux:")
			cmd.Println("  dvm completion zsh > \"${fpath[1]}/_dvm\"")
		case "fish":
			cmd.Println("  dvm completion fish > ~/.config/fish/completions/dvm.fish")
		case "powershell":
			cmd.Println("  dvm completion powershell > dvm.ps1")
			cmd.Println("  # Then add to your PowerShell profile")
		}

		cmd.Println()
		cmd.Println("Then restart your shell or source the completion file.")
	},
}

func init() {
	// Register custom completion functions for dynamic suggestions
	registerDynamicCompletions()
}

// registerDynamicCompletions registers custom completion functions
func registerDynamicCompletions() {
	// Complete workspace names for commands that accept workspace arguments
	workspaceCompletion := func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		// TODO: In the future, query the database for workspace names
		// For now, return empty (will use file completion)
		return []string{}, cobra.ShellCompDirectiveDefault
	}

	// Complete template names for 'dvm nvim init'
	templateCompletion := func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		templates := []string{
			"kickstart\tMinimal, well-documented starter config",
			"lazyvim\tFeature-rich, batteries-included config",
			"astronvim\tAesthetically pleasing, fully featured config",
			"minimal\tMinimal config created by DevOpsMaestro",
			"custom\tClone from custom Git URL",
		}
		return templates, cobra.ShellCompDirectiveNoFileComp
	}

	// Register completions for nvim commands
	if nvimInitCmd != nil {
		nvimInitCmd.ValidArgsFunction = templateCompletion
	}

	if nvimSyncCmd != nil {
		nvimSyncCmd.ValidArgsFunction = workspaceCompletion
	}

	if nvimPushCmd != nil {
		nvimPushCmd.ValidArgsFunction = workspaceCompletion
	}

	// Register hierarchy flag completions for commands that use them
	registerHierarchyCompletionsForAllCommands()
}

// registerHierarchyCompletionsForAllCommands finds all commands with hierarchy flags and registers completions
func registerHierarchyCompletionsForAllCommands() {
	// We need to register these after all commands are initialized
	// This function will be called from init() after all commands are set up

	if attachCmd != nil {
		registerHierarchyFlagCompletions(attachCmd)
	}

	if buildCmd != nil {
		registerHierarchyFlagCompletions(buildCmd)
	}

	if detachCmd != nil {
		registerHierarchyFlagCompletions(detachCmd)
	}

	if getWorkspacesCmd != nil {
		registerHierarchyFlagCompletions(getWorkspacesCmd)
	}

	if getWorkspaceCmd != nil {
		registerHierarchyFlagCompletions(getWorkspaceCmd)
	}
}
