// Package wezterm provides types and utilities for WezTerm terminal configuration management.
package wezterm

import (
	"fmt"
	"strings"
	"text/template"
)

// Generator is the interface for WezTerm configuration generators.
type Generator interface {
	Generate(spec *WeztermSpec) (string, error)
	GenerateFromConfig(config *WezTerm) (string, error)
}

// LuaGenerator generates WezTerm Lua configuration files.
type LuaGenerator struct {
	template *template.Template
}

// NewLuaGenerator creates a new LuaGenerator.
func NewLuaGenerator() *LuaGenerator {
	tmpl := template.Must(template.New("wezterm").Funcs(template.FuncMap{
		"formatLuaString":   formatLuaString,
		"formatLuaTable":    formatLuaTable,
		"formatKeyArgs":     formatKeyArgs,
		"formatStringSlice": formatStringSlice,
		"join":              strings.Join,
	}).Parse(luaTemplate))

	return &LuaGenerator{
		template: tmpl,
	}
}

// Generate creates a wezterm.lua configuration from a WeztermSpec.
func (g *LuaGenerator) Generate(spec *WeztermSpec) (string, error) {
	if spec == nil {
		return "", fmt.Errorf("spec is nil")
	}

	var buf strings.Builder
	err := g.template.Execute(&buf, spec)
	if err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// GenerateFromConfig creates a wezterm.lua configuration from a WezTerm config.
func (g *LuaGenerator) GenerateFromConfig(config *WezTerm) (string, error) {
	if config == nil {
		return "", fmt.Errorf("config is nil")
	}

	// Convert to WeztermSpec for template
	yamlConfig := config.ToYAML()
	return g.Generate(&yamlConfig.Spec)
}

// formatLuaString formats a string for Lua with proper escaping.
func formatLuaString(s string) string {
	if s == "" {
		return `""`
	}
	// Escape quotes and backslashes
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return fmt.Sprintf(`"%s"`, s)
}

// formatLuaTable formats key-value pairs as a Lua table.
func formatLuaTable(m map[string]any, indent int) string {
	if len(m) == 0 {
		return "{}"
	}

	indentStr := strings.Repeat("  ", indent)
	childIndentStr := strings.Repeat("  ", indent+1)

	var parts []string
	parts = append(parts, "{")

	for k, v := range m {
		var value string
		switch val := v.(type) {
		case string:
			value = formatLuaString(val)
		case int:
			value = fmt.Sprintf("%d", val)
		case int64:
			value = fmt.Sprintf("%d", val)
		case float64:
			value = fmt.Sprintf("%.2f", val)
		case bool:
			value = fmt.Sprintf("%t", val)
		case []string:
			value = "{ " + strings.Join(formatStringSlice(val), ", ") + " }"
		case map[string]any:
			value = formatLuaTable(val, indent+1)
		default:
			value = fmt.Sprintf("%v", val)
		}
		parts = append(parts, fmt.Sprintf("%s%s = %s,", childIndentStr, k, value))
	}

	parts = append(parts, indentStr+"}")
	return strings.Join(parts, "\n")
}

// formatStringSlice formats a string slice for Lua.
func formatStringSlice(slice []string) []string {
	result := make([]string, len(slice))
	for i, s := range slice {
		result[i] = formatLuaString(s)
	}
	return result
}

// formatKeyArgs formats keybinding arguments for Lua.
func formatKeyArgs(args any) string {
	if args == nil {
		return ""
	}

	switch val := args.(type) {
	case string:
		return formatLuaString(val)
	case map[string]any:
		return formatLuaTable(val, 0)
	case []any:
		var parts []string
		for _, item := range val {
			parts = append(parts, formatKeyArgs(item))
		}
		return "{ " + strings.Join(parts, ", ") + " }"
	default:
		return fmt.Sprintf("%v", val)
	}
}

// luaTemplate is the Lua template for WezTerm configuration.
const luaTemplate = `local wezterm = require("wezterm")
local act = wezterm.action
local config = wezterm.config_builder()

-- Configuration generated by DevOpsMaestro
{{- if .Colors}}

-- Colors
config.colors = {
  foreground = {{formatLuaString .Colors.Foreground}},
  background = {{formatLuaString .Colors.Background}},
  cursor_bg = {{formatLuaString .Colors.CursorBg}},
  cursor_fg = {{formatLuaString .Colors.CursorFg}},{{if .Colors.CursorBorder}}
  cursor_border = {{formatLuaString .Colors.CursorBorder}},{{end}}
  selection_bg = {{formatLuaString .Colors.SelectionBg}},
  selection_fg = {{formatLuaString .Colors.SelectionFg}},{{if .Colors.ANSI}}
  ansi = { {{join (formatStringSlice .Colors.ANSI) ", "}} },{{end}}{{if .Colors.Brights}}
  brights = { {{join (formatStringSlice .Colors.Brights) ", "}} },{{end}}
}
{{- end}}
{{- if .ThemeRef}}

-- Theme reference: {{.ThemeRef}}
-- Note: Theme colors would be loaded here from the theme system
{{- end}}

-- Font
config.font = wezterm.font({{formatLuaString .Font.Family}})
config.font_size = {{.Font.Size}}

-- Window
config.window_background_opacity = {{.Window.Opacity}}{{if .Window.Blur}}
config.macos_window_background_blur = {{.Window.Blur}}{{end}}{{if .Window.Decorations}}
config.window_decorations = {{formatLuaString .Window.Decorations}}{{end}}{{if .Window.InitialRows}}
config.initial_rows = {{.Window.InitialRows}}{{end}}{{if .Window.InitialCols}}
config.initial_cols = {{.Window.InitialCols}}{{end}}{{if .Window.CloseOnExit}}
config.exit_behavior = {{formatLuaString .Window.CloseOnExit}}{{end}}{{if or .Window.PaddingLeft .Window.PaddingRight .Window.PaddingTop .Window.PaddingBottom}}
config.window_padding = {
  left = {{.Window.PaddingLeft}},
  right = {{.Window.PaddingRight}},
  top = {{.Window.PaddingTop}},
  bottom = {{.Window.PaddingBottom}},
}{{end}}
{{- if .Scrollback}}

-- Scrollback
config.scrollback_lines = {{.Scrollback}}
{{- end}}
{{- if .Workspace}}

-- Default workspace
config.default_workspace = {{formatLuaString .Workspace}}
{{- end}}
{{- if .Leader}}

-- Leader key
config.leader = { key = {{formatLuaString .Leader.Key}}, mods = {{formatLuaString .Leader.Mods}}, timeout_milliseconds = {{.Leader.Timeout}} }
{{- end}}
{{- if .Keys}}

-- Key bindings
config.keys = {
{{- range .Keys}}
  { key = {{formatLuaString .Key}}, {{if .Mods}}mods = {{formatLuaString .Mods}}, {{end}}action = act.{{.Action}}{{if .Args}}({{formatKeyArgs .Args}}){{end}} },
{{- end}}
}
{{- end}}
{{- if .KeyTables}}

-- Key tables
config.key_tables = {
{{- range $tableName, $bindings := .KeyTables}}
  {{$tableName}} = {
{{- range $bindings}}
    { key = {{formatLuaString .Key}}, {{if .Mods}}mods = {{formatLuaString .Mods}}, {{end}}action = act.{{.Action}}{{if .Args}}({{formatKeyArgs .Args}}){{end}} },
{{- end}}
  },
{{- end}}
}
{{- end}}
{{- if .TabBar}}

-- Tab bar
{{- if not .TabBar.Enabled}}
config.enable_tab_bar = false
{{- else}}
config.enable_tab_bar = true{{if .TabBar.Position}}
config.tab_bar_at_bottom = {{eq .TabBar.Position "Bottom"}}{{end}}{{if .TabBar.MaxWidth}}
config.tab_max_width = {{.TabBar.MaxWidth}}{{end}}{{if .TabBar.FancyTabBar}}
config.use_fancy_tab_bar = {{.TabBar.FancyTabBar}}{{end}}{{if .TabBar.HideTabBarIfOnly}}
config.hide_tab_bar_if_only_one_tab = {{.TabBar.HideTabBarIfOnly}}{{end}}
{{- end}}
{{- end}}
{{- if .Pane}}

-- Pane configuration
{{- if .Pane.InactiveSaturation}}
config.inactive_pane_hsb = {
  saturation = {{.Pane.InactiveSaturation}},
  brightness = {{.Pane.InactiveBrightness}},
}
{{- end}}
{{- end}}
{{- if .Plugins}}

-- Plugins
{{- range .Plugins}}
-- Plugin: {{.Name}} ({{.Source}})
{{- if .Config}}
-- Configuration: {{formatLuaTable .Config 0}}
{{- end}}
{{- end}}
{{- end}}

return config`
