package builders

import (
	"fmt"
	"strings"

	"devopsmaestro/utils"
)

// generateCICDDockerfile produces the full Dockerfile for KindCICD apps:
// alpine:3.20 base + pinned-checksum kubectl/helm/kustomize (always) and argocd
// (gated on .argocd/), plus apk-installed leaf utilities. Honors the existing
// non-root dev-user flow (refs #56, #97) and the additional/required build-args
// surface (proxy etc.). See #404 §4 and the engineering-lead reconciliation.
//
// This is a separate code path from the language switch — it deliberately does
// not invoke generateBaseStage()/generateDevStage(), which are language-tooling
// oriented (apt-get, backports, polyglot dev tools, NodeSource, Mason).
func (g *DefaultDockerfileGenerator) generateCICDDockerfile() (string, error) {
	var df strings.Builder

	df.WriteString("# syntax=docker/dockerfile:1\n")
	df.WriteString("# Generated by DevOpsMaestro — KindCICD app (#404)\n")
	df.WriteString("# Alpine base + pinned-checksum kubectl/helm/kustomize/(argocd)\n")
	df.WriteString("# Base images pinned to SHA256 digests for reproducible builds\n\n")

	// Resolve private-repo info (proxy/auth detection)
	privateRepoInfo := g.privateRepoInfo
	if privateRepoInfo == nil {
		privateRepoInfo = utils.DetectPrivateRepos(g.appPath, g.language)
	}

	// CICD path is always Alpine — set the invariant so downstream helpers
	// (generateDevUser, isAlpineImage) take the apk/BusyBox path.
	g.isAlpine = true

	// Base stage
	baseImage := "alpine:3.20"
	df.WriteString(pinnedImageComment(baseImage))
	df.WriteString(fmt.Sprintf("FROM %s AS base\n\n", pinnedImage(baseImage)))

	// Required build args (proxy etc.) must be re-declared in this stage.
	if len(privateRepoInfo.RequiredBuildArgs) > 0 {
		df.WriteString("# Required build arguments (proxy, registry, etc.)\n")
		for _, a := range privateRepoInfo.RequiredBuildArgs {
			df.WriteString(fmt.Sprintf("ARG %s\n", a))
		}
		df.WriteString("\n")
	}
	g.emitAdditionalBuildArgs(&df, privateRepoInfo.RequiredBuildArgs)

	// CA certificate injection (so HTTPS to corporate mirrors works)
	g.emitCACertSection(&df)

	// Leaf utilities — well-vetted Alpine packages, acceptable per security review
	df.WriteString("# Leaf utilities for the CICD shell environment\n")
	df.WriteString(g.apkCacheMounts())
	df.WriteString("    apk add --no-cache git curl bash jq yq zsh ca-certificates\n\n")

	// Builder stages (kubectl, helm, kustomize, optional argocd, lazygit, starship)
	stages := g.activeBuilderStages()
	g.emitBuilderStages(&df, stages)

	// Dev stage
	df.WriteString("# Development stage with CICD tooling\n")
	df.WriteString("FROM base AS dev\n\n")
	df.WriteString("USER root\n\n")
	g.emitAdditionalBuildArgs(&df, privateRepoInfo.RequiredBuildArgs)

	g.emitCopyFromBuilders(&df, stages)

	// Create non-root dev user (refs #56, #97). g.isAlpine=true → BusyBox path.
	g.generateDevUser(&df)

	workdir := g.workspaceYAML.Container.WorkingDir
	if workdir == "" {
		workdir = "/workspace"
	}
	user := g.effectiveUser()
	df.WriteString("# Ensure workspace directory exists with correct ownership\n")
	df.WriteString(fmt.Sprintf("RUN mkdir -p %s && chown %s:%s %s\n\n", workdir, user, user, workdir))

	// Switch to non-root user — final USER directive in image
	df.WriteString(fmt.Sprintf("USER %s\n\n", user))
	df.WriteString(fmt.Sprintf("WORKDIR %s\n\n", workdir))

	if len(g.workspaceYAML.Container.Command) > 0 {
		cmd := strings.Join(g.workspaceYAML.Container.Command, "\", \"")
		df.WriteString(fmt.Sprintf("CMD [\"%s\"]\n", cmd))
	} else {
		df.WriteString("CMD [\"/bin/bash\", \"-c\", \"tail -f /dev/null\"]\n")
	}

	return df.String(), nil
}

// cicdBuilderStages returns the gated builder-stage list for KindCICD images.
// Always: kubectl, helm, kustomize, lazygit. Conditional: argocd (.argocd/),
// starship (theme=starship|empty). Explicitly skips Neovim/Tree-sitter/Go-tools/opencode.
func (g *DefaultDockerfileGenerator) cicdBuilderStages() []builderStage {
	stages := []builderStage{
		{
			name:     "kubectl-builder",
			emitFunc: g.generateKubectlBuilder,
			copyLines: []string{
				"COPY --from=kubectl-builder /usr/local/bin/kubectl /usr/local/bin/kubectl",
			},
		},
		{
			name:     "helm-builder",
			emitFunc: g.generateHelmBuilder,
			copyLines: []string{
				"COPY --from=helm-builder /usr/local/bin/helm /usr/local/bin/helm",
			},
		},
		{
			name:     "kustomize-builder",
			emitFunc: g.generateKustomizeBuilder,
			copyLines: []string{
				"COPY --from=kustomize-builder /usr/local/bin/kustomize /usr/local/bin/kustomize",
			},
		},
	}

	if g.argoCDDetected {
		stages = append(stages, builderStage{
			name:     "argocd-builder",
			emitFunc: g.generateArgoCDBuilder,
			copyLines: []string{
				"COPY --from=argocd-builder /usr/local/bin/argocd /usr/local/bin/argocd",
			},
		})
	}

	// Lazygit (always for the CICD shell)
	stages = append(stages, builderStage{
		name: "lazygit-builder",
		emitFunc: func(df *strings.Builder) {
			g.generateLazygitBuilder(df, true)
		},
		copyLines: []string{
			"COPY --from=lazygit-builder /usr/local/bin/lazygit /usr/local/bin/lazygit",
		},
	})

	// Starship (gated like the language path)
	if g.workspaceYAML.Shell.Theme == "starship" || g.workspaceYAML.Shell.Theme == "" {
		stages = append(stages, builderStage{
			name:     "starship-builder",
			emitFunc: g.generateStarshipBuilderAlpine,
			copyLines: []string{
				"COPY --from=starship-builder /usr/local/bin/starship /usr/local/bin/starship",
			},
		})
	}

	return stages
}
