package builders

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"devopsmaestro/models"
	"devopsmaestro/pkg/nvimops/plugin"
	"devopsmaestro/utils"
)

// DockerfileGenerator defines the interface for generating Dockerfiles for dev containers.
// Implementations produce Dockerfile content optimized with BuildKit features
// (parallel multi-stage builds, cache mounts) for a specific language/workspace combination.
type DockerfileGenerator interface {
	// SetPluginManifest sets the plugin manifest for conditional feature detection.
	// This should be called before Generate() to enable plugin-aware Dockerfile generation.
	SetPluginManifest(manifest *plugin.PluginManifest)

	// Generate creates a Dockerfile.dvm with dev stage.
	// Uses BuildKit features: parallel multi-stage builds, cache mounts.
	Generate() (string, error)
}

// Compile-time interface compliance check
var _ DockerfileGenerator = (*DefaultDockerfileGenerator)(nil)

// DefaultDockerfileGenerator is the standard implementation of DockerfileGenerator
// that generates Dockerfiles for dev containers.
type DefaultDockerfileGenerator struct {
	workspace      *models.Workspace
	workspaceYAML  models.WorkspaceSpec
	language       string
	version        string
	appPath        string
	baseDockerfile string
	pluginManifest *plugin.PluginManifest
}

// NewDockerfileGenerator creates a new Dockerfile generator.
// Returns the DockerfileGenerator interface for loose coupling.
func NewDockerfileGenerator(ws *models.Workspace, wsYAML models.WorkspaceSpec, lang, version, appPath, baseDockerfile string) DockerfileGenerator {
	return &DefaultDockerfileGenerator{
		workspace:      ws,
		workspaceYAML:  wsYAML,
		language:       lang,
		version:        version,
		appPath:        appPath,
		baseDockerfile: baseDockerfile,
	}
}

// SetPluginManifest sets the plugin manifest for conditional feature detection.
// This should be called before Generate() to enable plugin-aware Dockerfile generation.
func (g *DefaultDockerfileGenerator) SetPluginManifest(manifest *plugin.PluginManifest) {
	g.pluginManifest = manifest
}

// Generate creates a Dockerfile.dvm with dev stage
// Uses BuildKit features: parallel multi-stage builds, cache mounts
func (g *DefaultDockerfileGenerator) Generate() (string, error) {
	var dockerfile strings.Builder

	// Header comment
	dockerfile.WriteString("# syntax=docker/dockerfile:1\n")
	dockerfile.WriteString("# Generated by DevOpsMaestro\n")
	dockerfile.WriteString("# Development container with tools for coding\n")
	dockerfile.WriteString("# Optimized with BuildKit: parallel stages + cache mounts\n\n")

	// Detect private repository usage
	privateRepoInfo := utils.DetectPrivateRepos(g.appPath, g.language)

	// Add ARG declarations for build-time variables
	if len(privateRepoInfo.RequiredBuildArgs) > 0 {
		dockerfile.WriteString("# Build arguments for private repositories\n")
		for _, arg := range privateRepoInfo.RequiredBuildArgs {
			dockerfile.WriteString(fmt.Sprintf("ARG %s\n", arg))
		}
		dockerfile.WriteString("\n")
	}

	// For MVP: Always generate from scratch
	// Future: Support extending existing production Dockerfiles
	g.generateBaseStage(&dockerfile, privateRepoInfo)

	// Parallel builder stages - BuildKit runs these concurrently
	g.generateBuilderStages(&dockerfile)

	// Dev stage
	dockerfile.WriteString("# Development stage with additional tools\n")
	dockerfile.WriteString("FROM base AS dev\n\n")

	// Switch to root for installing dev tools
	dockerfile.WriteString("USER root\n\n")

	// Copy binaries from parallel builder stages
	g.copyFromBuilders(&dockerfile)

	// Generate dev stage content based on language and config
	g.generateDevStage(&dockerfile)

	// Create dev user if not exists
	g.generateDevUser(&dockerfile)

	// Add Neovim configuration after user is created
	g.generateNvimSection(&dockerfile)

	// Switch to dev user
	dockerfile.WriteString("USER dev\n\n")

	// Set working directory
	workdir := g.workspaceYAML.Container.WorkingDir
	if workdir == "" {
		workdir = "/workspace"
	}
	dockerfile.WriteString(fmt.Sprintf("WORKDIR %s\n\n", workdir))

	// Set command
	if len(g.workspaceYAML.Container.Command) > 0 {
		cmd := strings.Join(g.workspaceYAML.Container.Command, "\", \"")
		dockerfile.WriteString(fmt.Sprintf("CMD [\"%s\"]\n", cmd))
	} else {
		// Default to a long-running process
		dockerfile.WriteString("CMD [\"/bin/zsh\", \"-c\", \"tail -f /dev/null\"]\n")
	}

	return dockerfile.String(), nil
}

func (g *DefaultDockerfileGenerator) generateBaseStage(dockerfile *strings.Builder, privateRepoInfo *utils.PrivateRepoInfo) {
	dockerfile.WriteString("# Base stage (auto-generated)\n")

	switch g.language {
	case "python":
		version := g.version
		if version == "" {
			version = "3.11"
		}
		dockerfile.WriteString(fmt.Sprintf("FROM python:%s-slim-bookworm AS base\n\n", version))

		// Install git if needed for private repos
		if privateRepoInfo.NeedsGit {
			packages := []string{"git", "build-essential"}
			if privateRepoInfo.NeedsSSH {
				packages = append(packages, "openssh-client")
			}

			dockerfile.WriteString("# Install git for private repositories\n")
			dockerfile.WriteString("RUN --mount=type=cache,target=/var/cache/apt \\\n")
			dockerfile.WriteString("    --mount=type=cache,target=/var/lib/apt/lists \\\n")
			dockerfile.WriteString("    apt-get update && apt-get install -y --no-install-recommends --fix-broken \\\n")
			for _, pkg := range packages {
				dockerfile.WriteString(fmt.Sprintf("    %s \\\n", pkg))
			}
			// Remove trailing backslash - end the command
			// Actually, we need to just end cleanly. With cache mounts, no cleanup needed.
			dockerfile.WriteString("    && true\n\n")

			// Setup SSH for git if needed
			if privateRepoInfo.NeedsSSH {
				dockerfile.WriteString("# Setup SSH for git operations\n")
				dockerfile.WriteString("RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh\n")
				dockerfile.WriteString("# Mount SSH keys at build time using BuildKit secrets:\n")
				dockerfile.WriteString("# --mount=type=ssh\n")
				dockerfile.WriteString("RUN --mount=type=ssh \\\n")
				dockerfile.WriteString("    ssh-keyscan github.com >> /root/.ssh/known_hosts && \\\n")
				dockerfile.WriteString("    ssh-keyscan gitlab.com >> /root/.ssh/known_hosts\n\n")
			}
		} else {
			dockerfile.WriteString("# Install build dependencies\n")
			dockerfile.WriteString("RUN --mount=type=cache,target=/var/cache/apt \\\n")
			dockerfile.WriteString("    --mount=type=cache,target=/var/lib/apt/lists \\\n")
			dockerfile.WriteString("    apt-get update && \\\n")
			dockerfile.WriteString("    apt-get install -y --no-install-recommends --fix-broken \\\n")
			dockerfile.WriteString("    build-essential\n\n")
		}

		// For Python with SSH keys, install deps with SSH mount
		if privateRepoInfo.NeedsSSH {
			dockerfile.WriteString("# Install dependencies with SSH key mount\n")
			dockerfile.WriteString("COPY requirements.txt /tmp/\n")
			dockerfile.WriteString("RUN --mount=type=ssh \\\n")
			dockerfile.WriteString("    --mount=type=cache,target=/root/.cache/pip \\\n")
			dockerfile.WriteString("    pip install -r /tmp/requirements.txt\n\n")
		} else if len(privateRepoInfo.RequiredBuildArgs) > 0 {
			dockerfile.WriteString("# Copy and process requirements with build args\n")
			dockerfile.WriteString("COPY requirements.txt /tmp/requirements-template.txt\n")

			// Use shell to substitute variables
			dockerfile.WriteString("RUN cat /tmp/requirements-template.txt | \\\n")
			for _, arg := range privateRepoInfo.RequiredBuildArgs {
				dockerfile.WriteString(fmt.Sprintf("    sed \"s/\\${%s}/$%s/g\" | \\\n", arg, arg))
			}
			dockerfile.WriteString("    tee /tmp/requirements.txt > /dev/null\n\n")

			dockerfile.WriteString("RUN --mount=type=cache,target=/root/.cache/pip \\\n")
			dockerfile.WriteString("    pip install -r /tmp/requirements.txt\n\n")
		} else {
			dockerfile.WriteString("# Copy requirements and install\n")
			dockerfile.WriteString("COPY requirements.txt /tmp/\n")
			dockerfile.WriteString("RUN --mount=type=cache,target=/root/.cache/pip \\\n")
			dockerfile.WriteString("    pip install -r /tmp/requirements.txt\n\n")
		}

	case "golang":
		version := g.version
		if version == "" {
			version = "1.22"
		}
		dockerfile.WriteString(fmt.Sprintf("FROM golang:%s-alpine AS base\n\n", version))

		dockerfile.WriteString("# Install basic dependencies\n")
		dockerfile.WriteString("RUN --mount=type=cache,target=/var/cache/apk \\\n")
		dockerfile.WriteString("    apk add git\n\n")

		// Configure git for private repos with token
		if privateRepoInfo.NeedsGitConfig {
			dockerfile.WriteString("# Configure git for private repositories\n")
			for _, arg := range privateRepoInfo.RequiredBuildArgs {
				if arg == "GITHUB_TOKEN" {
					dockerfile.WriteString(fmt.Sprintf("ARG %s\n", arg))
					dockerfile.WriteString("RUN git config --global url.\"https://${GITHUB_TOKEN}@github.com/\".insteadOf \"https://github.com/\"\n\n")
				}
			}
		}

	case "nodejs":
		version := g.version
		if version == "" {
			version = "18"
		}
		dockerfile.WriteString(fmt.Sprintf("FROM node:%s-alpine AS base\n\n", version))

		if privateRepoInfo.NeedsGit {
			dockerfile.WriteString("# Install git for private repositories\n")
			dockerfile.WriteString("RUN --mount=type=cache,target=/var/cache/apk \\\n")
			dockerfile.WriteString("    apk add git\n\n")
		}

		// Setup .npmrc for private packages
		if len(privateRepoInfo.RequiredBuildArgs) > 0 {
			dockerfile.WriteString("# Configure npm for private packages\n")
			for _, arg := range privateRepoInfo.RequiredBuildArgs {
				if arg == "NPM_TOKEN" {
					dockerfile.WriteString(fmt.Sprintf("ARG %s\n", arg))
					dockerfile.WriteString("RUN echo \"//registry.npmjs.org/:_authToken=${NPM_TOKEN}\" > ~/.npmrc\n\n")
				}
			}
		}

	default:
		// Generic Ubuntu base
		dockerfile.WriteString("FROM ubuntu:22.04 AS base\n\n")

		packages := []string{"ca-certificates"}
		if privateRepoInfo.NeedsGit {
			packages = append(packages, "git")
		}

		dockerfile.WriteString("RUN --mount=type=cache,target=/var/cache/apt \\\n")
		dockerfile.WriteString("    --mount=type=cache,target=/var/lib/apt/lists \\\n")
		dockerfile.WriteString("    apt-get update && apt-get install -y --no-install-recommends --fix-broken \\\n")
		for i, pkg := range packages {
			if i < len(packages)-1 {
				dockerfile.WriteString(fmt.Sprintf("    %s \\\n", pkg))
			} else {
				dockerfile.WriteString(fmt.Sprintf("    %s\n", pkg))
			}
		}
		dockerfile.WriteString("\n")
	}
}

// generateBuilderStages emits parallel multi-stage builds for binary downloads.
// BuildKit runs these concurrently since they have no dependencies on each other.
//
// Builder image selection rationale:
//   - Neovim (Debian only): GitHub releases are glibc-linked, won't work on Alpine musl.
//     Alpine gets neovim via apk in the merged package install instead.
//   - Lazygit: Uses matching base (Alpine for Alpine targets, Debian for Debian) because
//     the binary is statically linked but download tools (curl vs wget, sed behavior) differ.
//   - Starship: Always Debian because the install script requires bash.
//   - Tree-sitter CLI: Alpine (small image, binary is statically linked).
//   - Go tools: Uses the same golang:X-alpine image as the base stage for ABI compatibility.
//
// Cache mount strategy: Builder stages do NOT use cache mounts because they are short-lived
// throwaway stages. Cache mounts on parallel stages can also cause lock contention.
// The dev stage (long-lived) does use cache mounts for all package managers.
func (g *DefaultDockerfileGenerator) generateBuilderStages(dockerfile *strings.Builder) {
	isAlpine := g.isAlpineImage()

	// Neovim builder (only for Debian - Alpine uses apk)
	if !isAlpine {
		g.generateNeovimBuilder(dockerfile)
	}

	// Lazygit builder
	g.generateLazygitBuilder(dockerfile, isAlpine)

	// Starship builder
	if g.workspaceYAML.Shell.Theme == "starship" || g.workspaceYAML.Shell.Theme == "" {
		g.generateStarshipBuilder(dockerfile)
	}

	// Tree-sitter CLI builder
	g.generateTreeSitterBuilder(dockerfile)

	// Go tools builder (only for golang workspaces with go-installable tools)
	if g.hasGoToolsBuilder() {
		g.generateGoToolsBuilder(dockerfile)
	}
}

// generateNeovimBuilder creates a parallel stage to download Neovim (Debian only)
func (g *DefaultDockerfileGenerator) generateNeovimBuilder(dockerfile *strings.Builder) {
	dockerfile.WriteString("# --- Parallel builder: Neovim ---\n")
	dockerfile.WriteString("FROM debian:bookworm-slim AS neovim-builder\n")
	dockerfile.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && \\\n")
	dockerfile.WriteString("    ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m) && \\\n")
	dockerfile.WriteString("    if [ \"$ARCH\" = \"arm64\" ] || [ \"$ARCH\" = \"aarch64\" ]; then \\\n")
	dockerfile.WriteString("        NVIM_ARCH=\"nvim-linux-arm64\"; \\\n")
	dockerfile.WriteString("    elif [ \"$ARCH\" = \"amd64\" ] || [ \"$ARCH\" = \"x86_64\" ]; then \\\n")
	dockerfile.WriteString("        NVIM_ARCH=\"nvim-linux-x86_64\"; \\\n")
	dockerfile.WriteString("    else \\\n")
	dockerfile.WriteString("        NVIM_ARCH=\"nvim-linux-x86_64\"; \\\n")
	dockerfile.WriteString("    fi && \\\n")
	dockerfile.WriteString("    curl -LO \"https://github.com/neovim/neovim/releases/latest/download/${NVIM_ARCH}.tar.gz\" && \\\n")
	dockerfile.WriteString("    tar -C /opt -xzf \"${NVIM_ARCH}.tar.gz\" && \\\n")
	dockerfile.WriteString("    mv /opt/${NVIM_ARCH} /opt/nvim && \\\n")
	dockerfile.WriteString("    rm \"${NVIM_ARCH}.tar.gz\"\n\n")
}

// generateLazygitBuilder creates a parallel stage to download lazygit
func (g *DefaultDockerfileGenerator) generateLazygitBuilder(dockerfile *strings.Builder, isAlpine bool) {
	dockerfile.WriteString("# --- Parallel builder: lazygit ---\n")
	if isAlpine {
		dockerfile.WriteString("FROM alpine:3.20 AS lazygit-builder\n")
		dockerfile.WriteString("RUN apk add --no-cache curl sed && \\\n")
		dockerfile.WriteString("    ARCH=$(uname -m) && \\\n")
		dockerfile.WriteString("    if [ \"$ARCH\" = \"aarch64\" ]; then \\\n")
		dockerfile.WriteString("        LG_ARCH=\"arm64\"; \\\n")
		dockerfile.WriteString("    elif [ \"$ARCH\" = \"x86_64\" ]; then \\\n")
		dockerfile.WriteString("        LG_ARCH=\"x86_64\"; \\\n")
		dockerfile.WriteString("    else \\\n")
		dockerfile.WriteString("        LG_ARCH=\"x86_64\"; \\\n")
		dockerfile.WriteString("    fi && \\\n")
	} else {
		dockerfile.WriteString("FROM debian:bookworm-slim AS lazygit-builder\n")
		dockerfile.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates sed && \\\n")
		dockerfile.WriteString("    ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m) && \\\n")
		dockerfile.WriteString("    if [ \"$ARCH\" = \"arm64\" ] || [ \"$ARCH\" = \"aarch64\" ]; then \\\n")
		dockerfile.WriteString("        LG_ARCH=\"arm64\"; \\\n")
		dockerfile.WriteString("    elif [ \"$ARCH\" = \"amd64\" ] || [ \"$ARCH\" = \"x86_64\" ]; then \\\n")
		dockerfile.WriteString("        LG_ARCH=\"x86_64\"; \\\n")
		dockerfile.WriteString("    else \\\n")
		dockerfile.WriteString("        LG_ARCH=\"x86_64\"; \\\n")
		dockerfile.WriteString("    fi && \\\n")
	}
	dockerfile.WriteString("    LAZYGIT_VERSION=$(curl -s \"https://api.github.com/repos/jesseduffield/lazygit/releases/latest\" | sed -n 's/.*\"tag_name\": \"v\\([^\"]*\\)\".*/\\1/p') && \\\n")
	dockerfile.WriteString("    curl -Lo lazygit.tar.gz \"https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_${LG_ARCH}.tar.gz\" && \\\n")
	dockerfile.WriteString("    tar xf lazygit.tar.gz lazygit && \\\n")
	dockerfile.WriteString("    install lazygit /usr/local/bin && \\\n")
	dockerfile.WriteString("    rm lazygit lazygit.tar.gz\n\n")
}

// generateStarshipBuilder creates a parallel stage to download Starship prompt
func (g *DefaultDockerfileGenerator) generateStarshipBuilder(dockerfile *strings.Builder) {
	dockerfile.WriteString("# --- Parallel builder: Starship prompt ---\n")
	dockerfile.WriteString("FROM debian:bookworm-slim AS starship-builder\n")
	dockerfile.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && \\\n")
	dockerfile.WriteString("    curl -sS https://starship.rs/install.sh | sh -s -- --yes\n\n")
}

// generateTreeSitterBuilder creates a parallel stage to download tree-sitter CLI
func (g *DefaultDockerfileGenerator) generateTreeSitterBuilder(dockerfile *strings.Builder) {
	dockerfile.WriteString("# --- Parallel builder: tree-sitter CLI ---\n")
	dockerfile.WriteString("FROM alpine:3.20 AS treesitter-builder\n")
	dockerfile.WriteString("RUN apk add --no-cache curl && \\\n")
	dockerfile.WriteString("    ARCH=$(uname -m) && \\\n")
	dockerfile.WriteString("    if [ \"$ARCH\" = \"aarch64\" ]; then TS_ARCH=\"arm64\"; \\\n")
	dockerfile.WriteString("    elif [ \"$ARCH\" = \"x86_64\" ]; then TS_ARCH=\"x64\"; \\\n")
	dockerfile.WriteString("    else TS_ARCH=\"x64\"; fi && \\\n")
	dockerfile.WriteString("    curl -sL \"https://github.com/tree-sitter/tree-sitter/releases/download/v0.24.6/tree-sitter-linux-${TS_ARCH}.gz\" -o /tmp/ts.gz && \\\n")
	dockerfile.WriteString("    gunzip /tmp/ts.gz && chmod +x /tmp/ts && mv /tmp/ts /usr/local/bin/tree-sitter\n\n")
}

// getGoToolsList returns the resolved Go tools list (config or defaults)
func (g *DefaultDockerfileGenerator) getGoToolsList() []string {
	tools := g.workspaceYAML.Build.DevStage.DevTools
	if len(tools) == 0 {
		tools = g.getDefaultLanguageTools()
	}
	return tools
}

// hasGoToolsBuilder returns true if we need a parallel Go tools builder stage.
// This is true when the language is golang and there are go-installable tools
// (i.e., tools other than golangci-lint which uses a curl installer).
func (g *DefaultDockerfileGenerator) hasGoToolsBuilder() bool {
	if g.language != "golang" {
		return false
	}
	for _, tool := range g.getGoToolsList() {
		if tool != "golangci-lint" {
			return true
		}
	}
	return false
}

// generateGoToolsBuilder creates a parallel stage to install Go dev tools
func (g *DefaultDockerfileGenerator) generateGoToolsBuilder(dockerfile *strings.Builder) {
	tools := g.getGoToolsList()

	var installCmds []string
	for _, tool := range tools {
		switch tool {
		case "gopls":
			installCmds = append(installCmds, "go install golang.org/x/tools/gopls@latest")
		case "delve":
			installCmds = append(installCmds, "go install github.com/go-delve/delve/cmd/dlv@latest")
		case "golangci-lint":
			// golangci-lint uses curl installer, not go install; handled in dev stage
		default:
			installCmds = append(installCmds, fmt.Sprintf("go install %s@latest", tool))
		}
	}

	if len(installCmds) == 0 {
		return
	}

	dockerfile.WriteString("# --- Parallel builder: Go tools ---\n")
	dockerfile.WriteString(fmt.Sprintf("FROM golang:%s-alpine AS go-tools-builder\n", g.effectiveGoVersion()))
	dockerfile.WriteString("RUN --mount=type=cache,target=/go/pkg/mod \\\n")
	dockerfile.WriteString("    --mount=type=cache,target=/root/.cache/go-build \\\n")
	dockerfile.WriteString("    " + strings.Join(installCmds, " && \\\n    ") + "\n\n")
}

// copyFromBuilders emits COPY --from= directives to pull binaries from parallel stages
func (g *DefaultDockerfileGenerator) copyFromBuilders(dockerfile *strings.Builder) {
	isAlpine := g.isAlpineImage()

	dockerfile.WriteString("# Copy binaries from parallel builder stages\n")

	// Neovim (Debian: from builder; Alpine: installed via apk in merged package install)
	if !isAlpine {
		dockerfile.WriteString("COPY --from=neovim-builder /opt/nvim/ /opt/nvim/\n")
		dockerfile.WriteString("RUN ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim\n")
	}

	// Lazygit
	dockerfile.WriteString("COPY --from=lazygit-builder /usr/local/bin/lazygit /usr/local/bin/lazygit\n")

	// Starship
	if g.workspaceYAML.Shell.Theme == "starship" || g.workspaceYAML.Shell.Theme == "" {
		dockerfile.WriteString("COPY --from=starship-builder /usr/local/bin/starship /usr/local/bin/starship\n")
	}

	// Tree-sitter CLI
	dockerfile.WriteString("COPY --from=treesitter-builder /usr/local/bin/tree-sitter /usr/local/bin/tree-sitter\n")

	// Go tools (only if parallel builder stage was emitted)
	if g.hasGoToolsBuilder() {
		dockerfile.WriteString("COPY --from=go-tools-builder /go/bin/ /go/bin/\n")
	}

	dockerfile.WriteString("\n")
}

// effectiveGoVersion returns the Go version to use (with default)
func (g *DefaultDockerfileGenerator) effectiveGoVersion() string {
	if g.version != "" {
		return g.version
	}
	return "1.22"
}

func (g *DefaultDockerfileGenerator) generateDevStage(dockerfile *strings.Builder) {
	// Get packages from config or use defaults
	packages := g.workspaceYAML.Build.DevStage.Packages
	if len(packages) == 0 {
		packages = g.getDefaultPackages()
	}

	isAlpine := g.isAlpineImage()

	// Merge all packages into a single install: dev packages + nvim deps + Mason toolchains
	// This eliminates redundant apt-get update/apk update calls
	allPackages := make([]string, 0, len(packages)+10)
	allPackages = append(allPackages, packages...)

	// Add nvim dependency packages (previously in installNvimDependencies)
	if g.workspaceYAML.Nvim.Structure != "none" {
		if isAlpine {
			allPackages = appendUnique(allPackages, "unzip", "build-base", "ripgrep", "fd")
			// Mason toolchains for Alpine
			allPackages = appendUnique(allPackages, "nodejs", "npm", "py3-pip", "cargo")
			// Neovim via apk (Alpine can't use GitHub releases - musl vs glibc)
			allPackages = appendUnique(allPackages, "neovim", "neovim-doc")
		} else {
			allPackages = appendUnique(allPackages, "unzip", "build-essential", "ripgrep", "fd-find")
			// Mason toolchains for Debian
			allPackages = appendUnique(allPackages, "nodejs", "npm", "python3-pip", "cargo")
		}
	}

	// Install all packages in one shot with cache mounts
	dockerfile.WriteString("# Install all dev tools, nvim dependencies, and Mason toolchains (merged)\n")
	if isAlpine {
		dockerfile.WriteString("RUN --mount=type=cache,target=/var/cache/apk \\\n")
		dockerfile.WriteString("    apk add \\\n")
	} else {
		dockerfile.WriteString("RUN --mount=type=cache,target=/var/cache/apt \\\n")
		dockerfile.WriteString("    --mount=type=cache,target=/var/lib/apt/lists \\\n")
		dockerfile.WriteString("    apt-get update && apt-get install -y --no-install-recommends --fix-broken \\\n")
	}

	for i, pkg := range allPackages {
		if i < len(allPackages)-1 {
			dockerfile.WriteString(fmt.Sprintf("    %s \\\n", pkg))
		} else {
			dockerfile.WriteString(fmt.Sprintf("    %s\n", pkg))
		}
	}
	dockerfile.WriteString("\n")

	// npm install neovim (needed by Mason) - with cache mount
	if g.workspaceYAML.Nvim.Structure != "none" {
		dockerfile.WriteString("# Install neovim npm package for Mason\n")
		dockerfile.WriteString("RUN --mount=type=cache,target=/root/.npm \\\n")
		dockerfile.WriteString("    npm install -g neovim\n\n")
	}

	// Install language-specific tools (non-Go, since Go tools come from parallel builder)
	languageTools := g.workspaceYAML.Build.DevStage.DevTools
	if len(languageTools) == 0 {
		languageTools = g.getDefaultLanguageTools()
	}
	if len(languageTools) > 0 && g.language != "golang" {
		g.installLanguageTools(dockerfile, languageTools)
	}

	// For golang, install golangci-lint separately (uses curl installer, not go install)
	if g.language == "golang" {
		for _, tool := range languageTools {
			if tool == "golangci-lint" {
				dockerfile.WriteString("# Install golangci-lint via installer script\n")
				dockerfile.WriteString("RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin\n\n")
				break
			}
		}
	}

	// Custom commands
	for _, cmd := range g.workspaceYAML.Build.DevStage.CustomCommands {
		dockerfile.WriteString(fmt.Sprintf("RUN %s\n", cmd))
	}

	if len(g.workspaceYAML.Build.DevStage.CustomCommands) > 0 {
		dockerfile.WriteString("\n")
	}
}

// appendUnique appends items to a slice only if they're not already present
func appendUnique(slice []string, items ...string) []string {
	existing := make(map[string]bool, len(slice))
	for _, s := range slice {
		existing[s] = true
	}
	for _, item := range items {
		if !existing[item] {
			slice = append(slice, item)
			existing[item] = true
		}
	}
	return slice
}

func (g *DefaultDockerfileGenerator) generateDevUser(dockerfile *strings.Builder) {
	uid := g.workspaceYAML.Container.UID
	gid := g.workspaceYAML.Container.GID
	user := g.workspaceYAML.Container.User

	if uid == 0 {
		uid = 1000
	}
	if gid == 0 {
		gid = 1000
	}
	if user == "" {
		user = "dev"
	}

	// Detect if this is an Alpine-based image
	isAlpine := g.isAlpineImage()

	if isAlpine {
		// Alpine: use addgroup/adduser (BusyBox)
		dockerfile.WriteString("# Create dev user (Alpine/BusyBox)\n")
		dockerfile.WriteString(fmt.Sprintf("RUN addgroup -g %d %s 2>/dev/null || true\n", gid, user))
		dockerfile.WriteString(fmt.Sprintf("RUN adduser -D -u %d -G %s -s /bin/zsh %s 2>/dev/null || true\n\n", uid, user, user))
	} else {
		// Debian/Ubuntu: use groupadd/useradd
		dockerfile.WriteString("# Create dev user (Debian/Ubuntu)\n")
		dockerfile.WriteString(fmt.Sprintf("RUN groupadd -g %d %s 2>/dev/null || true\n", gid, user))
		dockerfile.WriteString(fmt.Sprintf("RUN useradd -m -u %d -g %s -s /bin/zsh %s 2>/dev/null || true\n\n", uid, user, user))
	}

	// Copy shell configuration files from staging area
	dockerfile.WriteString("# Copy shell configuration\n")
	dockerfile.WriteString(fmt.Sprintf("COPY .zshrc /home/%s/.zshrc\n", user))
	dockerfile.WriteString(fmt.Sprintf("COPY .config/starship.toml /home/%s/.config/starship.toml\n", user))
	dockerfile.WriteString(fmt.Sprintf("RUN chown -R %s:%s /home/%s/.zshrc /home/%s/.config\n\n", user, user, user, user))
}

func (g *DefaultDockerfileGenerator) getDefaultPackages() []string {
	base := []string{
		"git",
		"curl",
		"wget",
		"zsh",
	}

	// Add language-specific base packages
	switch g.language {
	case "python":
		if !strings.Contains(g.workspace.ImageName, "alpine") {
			base = append(base, "build-essential", "python3-pip")
		}
	case "golang":
		// Go images usually have everything needed
	}

	return base
}

// isAlpineImage returns true if the base image is Alpine-based
// This affects user creation commands, package manager, and binary compatibility
func (g *DefaultDockerfileGenerator) isAlpineImage() bool {
	return g.language == "golang" || strings.Contains(g.workspace.ImageName, "alpine")
}

func (g *DefaultDockerfileGenerator) getDefaultLanguageTools() []string {
	switch g.language {
	case "python":
		return []string{"python-lsp-server", "black", "isort", "pytest"}
	case "golang":
		return []string{"gopls", "delve", "golangci-lint"}
	case "nodejs":
		return []string{"typescript", "ts-node"}
	default:
		return []string{}
	}
}

func (g *DefaultDockerfileGenerator) installLanguageTools(dockerfile *strings.Builder, tools []string) {
	dockerfile.WriteString("# Install language-specific tools\n")

	switch g.language {
	case "python":
		dockerfile.WriteString("RUN --mount=type=cache,target=/root/.cache/pip \\\n")
		dockerfile.WriteString("    pip install")
		for _, tool := range tools {
			dockerfile.WriteString(fmt.Sprintf(" %s", tool))
		}
		dockerfile.WriteString("\n\n")

	case "golang":
		// Go tools are installed in the parallel go-tools-builder stage
		// Only golangci-lint (curl installer) is handled separately in generateDevStage
		dockerfile.WriteString("# Go tools installed via parallel builder stage\n\n")

	case "nodejs":
		dockerfile.WriteString("RUN --mount=type=cache,target=/root/.npm \\\n")
		dockerfile.WriteString("    npm install -g")
		for _, tool := range tools {
			dockerfile.WriteString(fmt.Sprintf(" %s", tool))
		}
		dockerfile.WriteString("\n\n")
	}
}

// generateNvimSection copies nvim config and installs plugins (called after user creation)
func (g *DefaultDockerfileGenerator) generateNvimSection(dockerfile *strings.Builder) {
	// Skip if explicitly disabled
	if g.workspaceYAML.Nvim.Structure == "none" {
		return
	}

	// Check if staging nvim config directory exists
	// The copyNvimConfig function now creates config in staging directory
	homeDir, _ := os.UserHomeDir()
	stagingDir := filepath.Join(homeDir, ".devopsmaestro", "build-staging", filepath.Base(g.appPath))
	nvimConfigPath := filepath.Join(stagingDir, ".config", "nvim")
	if _, err := os.Stat(nvimConfigPath); os.IsNotExist(err) {
		// Nvim config doesn't exist - skip this section
		dockerfile.WriteString("# Skipping Neovim configuration (no config generated)\n")
		dockerfile.WriteString("# Run 'dvm build' after setting up nvim plugins to enable nvim config\n\n")
		return
	}

	// Copy nvim configuration from staging directory
	dockerfile.WriteString("# Copy Neovim configuration\n")
	dockerfile.WriteString("COPY .config/nvim /home/dev/.config/nvim\n")
	dockerfile.WriteString("RUN chown -R dev:dev /home/dev/.config\n\n")

	// tree-sitter CLI is already installed via parallel builder stage (COPY --from=treesitter-builder)

	// Install lazy.nvim and plugins as dev user with proper error handling
	dockerfile.WriteString("USER dev\n")
	dockerfile.WriteString("# Bootstrap lazy.nvim and install plugins\n")
	dockerfile.WriteString("RUN nvim --headless \"+Lazy! sync\" +qa 2>&1 | tee /tmp/nvim-install.log || \\\n")
	dockerfile.WriteString("    (cat /tmp/nvim-install.log && exit 1)\n\n")

	// Install Treesitter parsers at build time (reduces first-attach startup time)
	g.installTreesitterParsers(dockerfile)

	// Install Mason LSPs at build time (reduces first-attach startup time)
	g.installMasonLSPs(dockerfile)

	dockerfile.WriteString("USER root\n\n")
}

// getMasonLSPsForLanguage returns the Mason LSP package names for the detected language
func (g *DefaultDockerfileGenerator) getMasonLSPsForLanguage() []string {
	switch g.language {
	case "python":
		return []string{"pyright", "ruff-lsp", "black", "isort"}
	case "golang":
		return []string{"gopls", "golangci-lint-langserver"}
	case "nodejs":
		return []string{"typescript-language-server", "eslint-lsp", "prettier"}
	case "rust":
		return []string{"rust-analyzer"}
	case "ruby":
		return []string{"solargraph"}
	case "java":
		return []string{"jdtls"}
	case "gleam":
		return []string{"gleam"} // Gleam LSP is installed via Mason
	default:
		return []string{}
	}
}

// installMasonLSPs installs language servers via Mason at build time
func (g *DefaultDockerfileGenerator) installMasonLSPs(dockerfile *strings.Builder) {
	// Check if Mason is installed via manifest
	if g.pluginManifest != nil && !g.pluginManifest.Features.HasMason {
		dockerfile.WriteString("# Mason not installed - skipping LSP pre-install\n\n")
		return
	}

	lsps := g.getMasonLSPsForLanguage()
	if len(lsps) == 0 {
		return
	}

	dockerfile.WriteString("# Install LSPs via Mason at build time\n")
	// MasonInstall can accept multiple packages in a single command
	// Batch all LSPs together to reduce build layers and time
	lspList := strings.Join(lsps, " ")
	dockerfile.WriteString(fmt.Sprintf("RUN nvim --headless -c \"MasonInstall %s\" -c \"sleep 60\" -c \"qa\" 2>&1\n\n", lspList))
}

// getTreesitterParsersForLanguage returns Treesitter parsers for the detected language
func (g *DefaultDockerfileGenerator) getTreesitterParsersForLanguage() []string {
	// Base parsers always included for a good editing experience
	base := []string{"lua", "vim", "vimdoc", "query", "markdown", "markdown_inline", "bash", "json", "yaml"}

	switch g.language {
	case "python":
		return append(base, "python", "toml", "dockerfile", "gitignore")
	case "golang":
		return append(base, "go", "gomod", "gosum", "gowork", "dockerfile", "gitignore")
	case "nodejs":
		return append(base, "javascript", "typescript", "tsx", "html", "css", "dockerfile", "gitignore")
	case "rust":
		return append(base, "rust", "toml", "dockerfile", "gitignore")
	case "ruby":
		return append(base, "ruby", "dockerfile", "gitignore")
	case "java":
		return append(base, "java", "xml", "dockerfile", "gitignore")
	case "gleam":
		return append(base, "gleam", "erlang", "elixir", "toml", "dockerfile", "gitignore")
	default:
		return base
	}
}

// installTreesitterParsers installs Treesitter parsers at build time
func (g *DefaultDockerfileGenerator) installTreesitterParsers(dockerfile *strings.Builder) {
	// Check if Treesitter is installed via manifest
	if g.pluginManifest != nil && !g.pluginManifest.Features.HasTreesitter {
		dockerfile.WriteString("# Treesitter not installed - skipping parser pre-install\n\n")
		return
	}

	parsers := g.getTreesitterParsersForLanguage()
	if len(parsers) == 0 {
		return
	}

	dockerfile.WriteString("# Install Treesitter parsers at build time\n")
	// Use Lua API with :wait() for synchronous installation
	// The new nvim-treesitter API has require('nvim-treesitter').install():wait()
	// which blocks until parsers are fully compiled
	luaParsers := "'" + strings.Join(parsers, "', '") + "'"
	dockerfile.WriteString(fmt.Sprintf("RUN nvim --headless -c \"lua require('nvim-treesitter').install({%s}):wait()\" -c \"qa\" 2>&1\n\n", luaParsers))
}
