package builders

import (
	"devopsmaestro/models"
	"fmt"
	"path/filepath"
	"strings"
)

// SandboxNvimOptions controls the optional Neovim layer for a sandbox image.
//
// When IncludeNvim is true, GenerateSandboxDockerfileWithNvim emits:
//   - A parallel `neovim-builder` stage that downloads the pinned Neovim tarball
//     (with a build-from-source fallback when the host GLIBC is too old, mirroring
//     DefaultDockerfileGenerator's behavior).
//   - apt-get install of nvim runtime deps (ripgrep, fd-find, unzip, build-essential).
//   - A COPY of the pre-staged nvim config from the build context into
//     /home/dev/.config/nvim.
//   - A `lazy.nvim sync` headless invocation as the dev user to install plugins.
//
// We deliberately keep the sandbox install lighter than the full workspace path:
// no Mason toolchain pre-install, no Treesitter parser pre-build. Sandboxes are
// ephemeral, and Mason / Treesitter parsers can be installed on first use inside
// the running container without significantly extending build time.
type SandboxNvimOptions struct {
	// IncludeNvim toggles the entire Neovim layer. When false the generator falls
	// back to GenerateSandboxDockerfile's minimal output for byte-for-byte parity.
	IncludeNvim bool
}

// GenerateSandboxDockerfileWithNvim creates a Dockerfile for a sandbox image,
// optionally including a Neovim install + plugin sync layer.
//
// When opts.IncludeNvim is false, the output matches GenerateSandboxDockerfile
// exactly. When true, the generated Dockerfile assumes the build context contains
// a `.config/nvim/` directory with a fully-resolved nvim config (init.lua, plugin
// specs, theme files). See cmd/sandbox_nvim_stage.go for the staging helper that
// produces this directory.
func GenerateSandboxDockerfileWithNvim(
	preset models.SandboxPreset,
	version, depsFile string,
	opts SandboxNvimOptions,
) string {
	if !opts.IncludeNvim {
		return GenerateSandboxDockerfile(preset, version, depsFile)
	}

	var b strings.Builder

	// Header: enable BuildKit syntax so cache mounts + parallel stages work.
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# Generated by DevOpsMaestro (sandbox + nvim)\n\n")

	// Parallel Neovim builder — reuse the same constants and layout as
	// DefaultDockerfileGenerator.generateNeovimBuilder so behavior stays consistent.
	writeSandboxNeovimBuilder(&b)

	// Base sandbox image (language runtime + non-root user + deps + nvim copy).
	baseImage := preset.BaseImage(version)
	fmt.Fprintf(&b, "FROM %s\n\n", baseImage)

	// Essential tools + nvim runtime deps. Merging into one apt-get call keeps
	// the layer count low and matches the regular workspace pattern.
	b.WriteString("# Essential tools + Neovim runtime deps\n")
	b.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends \\\n")
	b.WriteString("    git curl ca-certificates build-essential \\\n")
	b.WriteString("    ripgrep fd-find unzip \\\n")
	b.WriteString("    && rm -rf /var/lib/apt/lists/*\n\n")

	// UV for Python-based presets — same as the minimal generator.
	isPython := preset.Language == "python" || preset.Language == "jupyter"
	if isPython {
		b.WriteString("# Install UV (fast Python package manager)\n")
		b.WriteString("COPY --from=ghcr.io/astral-sh/uv:0.7.2 /uv /uvx /bin/\n\n")
		b.WriteString("# Configure UV for container usage\n")
		b.WriteString("ENV UV_LINK_MODE=copy\n")
		b.WriteString("ENV UV_COMPILE_BYTECODE=1\n")
		b.WriteString("ENV UV_SYSTEM_PYTHON=1\n\n")
	}

	// Copy the Neovim binary from the parallel builder, then run the GLIBC
	// fallback test (build from source if the pre-built binary is incompatible).
	b.WriteString("# Install Neovim from parallel builder stage\n")
	b.WriteString("COPY --from=neovim-builder /opt/nvim/ /opt/nvim/\n")
	b.WriteString(sandboxNeovimGlibcFallbackRun())
	b.WriteString("\n\n")

	// Non-root dev user — created BEFORE the nvim config COPY so chown lands right.
	b.WriteString("# Create non-root dev user\n")
	b.WriteString("RUN groupadd -g 1000 dev && useradd -m -u 1000 -g dev -s /bin/bash dev\n\n")

	b.WriteString("# Working directory\n")
	b.WriteString("WORKDIR /sandbox\n")
	b.WriteString("RUN chown dev:dev /sandbox\n\n")

	// Copy pre-staged nvim config (generated by cmd/sandbox_nvim_stage.go) into
	// the dev user's home. The build context MUST contain `.config/nvim/`.
	b.WriteString("# Copy pre-generated Neovim configuration (from build context staging)\n")
	b.WriteString("COPY --chown=dev:dev .config/nvim /home/dev/.config/nvim\n\n")

	// Optional dependency install (matches the minimal generator's logic).
	if depsFile != "" {
		baseName := filepath.Base(depsFile)
		fmt.Fprintf(&b, "# Install dependencies\n")
		fmt.Fprintf(&b, "COPY %s /sandbox/%s\n", baseName, baseName)

		installCmd := preset.DepsInstallCmd
		if strings.Contains(installCmd, "%s") {
			installCmd = fmt.Sprintf(installCmd, baseName)
		}

		if isPython && strings.Contains(installCmd, "pip install") {
			uvCmd := strings.Replace(installCmd, "pip install", "uv pip install", 1)
			fmt.Fprintf(&b, "RUN %s || %s\n\n", uvCmd, installCmd)
		} else {
			fmt.Fprintf(&b, "RUN %s\n\n", installCmd)
		}
	}

	// Switch to dev user BEFORE bootstrapping lazy.nvim so plugins land in
	// /home/dev/.local/share/nvim with correct ownership.
	b.WriteString("USER dev\n\n")

	// Bootstrap lazy.nvim and sync plugins. We tee the log so the failure mode
	// surfaces in `dvm sandbox create` output rather than silently swallowing.
	// The same pattern is used by DefaultDockerfileGenerator.generateNvimSection.
	b.WriteString("# Bootstrap lazy.nvim and install plugins (headless)\n")
	b.WriteString("RUN nvim --headless \"+Lazy! sync\" +qa 2>&1 | tee /tmp/nvim-install.log || \\\n")
	b.WriteString("    (cat /tmp/nvim-install.log && exit 1)\n\n")

	b.WriteString("CMD [\"/bin/bash\"]\n")

	return b.String()
}

// writeSandboxNeovimBuilder emits the parallel Neovim builder stage used by
// GenerateSandboxDockerfileWithNvim. Kept as a package-private helper here
// (rather than reusing DefaultDockerfileGenerator.generateNeovimBuilder) so the
// sandbox path doesn't need a fully-constructed *DefaultDockerfileGenerator
// (which requires a *models.Workspace, plugin manifest, etc. that sandboxes lack).
func writeSandboxNeovimBuilder(b *strings.Builder) {
	b.WriteString("# --- Parallel builder: Neovim ---\n")
	fmt.Fprintf(b, "FROM %s AS neovim-builder\n", pinnedImage("debian:bookworm-slim"))
	b.WriteString("RUN set -e && \\\n")
	b.WriteString("    rm -rf /var/lib/apt/lists/* && apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && \\\n")
	b.WriteString("    ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m) && \\\n")
	b.WriteString("    if [ \"$ARCH\" = \"arm64\" ] || [ \"$ARCH\" = \"aarch64\" ]; then \\\n")
	fmt.Fprintf(b, "        NVIM_ARCH=\"nvim-linux-arm64\"; NVIM_SHA256=\"%s\"; \\\n", neovimTarballChecksumArm64)
	b.WriteString("    elif [ \"$ARCH\" = \"amd64\" ] || [ \"$ARCH\" = \"x86_64\" ]; then \\\n")
	fmt.Fprintf(b, "        NVIM_ARCH=\"nvim-linux-x86_64\"; NVIM_SHA256=\"%s\"; \\\n", neovimTarballChecksumX86_64)
	b.WriteString("    else \\\n")
	b.WriteString("        echo \"ERROR: Unsupported architecture: $ARCH\"; exit 1; \\\n")
	b.WriteString("    fi && \\\n")
	fmt.Fprintf(b, "    curl %s -o \"${NVIM_ARCH}.tar.gz\" \"https://github.com/neovim/neovim/releases/download/v%s/${NVIM_ARCH}.tar.gz\" && \\\n", curlFlags, neovimVersion)
	b.WriteString("    echo \"${NVIM_SHA256}  ${NVIM_ARCH}.tar.gz\" | sha256sum -c - && \\\n")
	b.WriteString("    mkdir -p /opt/nvim && \\\n")
	b.WriteString("    tar xzf \"${NVIM_ARCH}.tar.gz\" --strip-components=1 -C /opt/nvim && \\\n")
	b.WriteString("    rm \"${NVIM_ARCH}.tar.gz\" && \\\n")
	b.WriteString("    test -x /opt/nvim/bin/nvim\n\n")
}

// sandboxNeovimGlibcFallbackRun mirrors DefaultDockerfileGenerator.neovimGlibcFallbackRun.
// If the pre-built binary fails because the base image's GLIBC is too old (#342),
// we build Neovim from source. The symlink at the end is what puts `nvim` on PATH.
func sandboxNeovimGlibcFallbackRun() string {
	return fmt.Sprintf(`RUN if /opt/nvim/bin/nvim --version > /dev/null 2>&1; then \
      echo "Neovim pre-built binary OK"; \
    else \
      echo "Neovim pre-built binary incompatible (GLIBC too old), building from source..."; \
      rm -rf /var/lib/apt/lists/* && apt-get update && apt-get install -y --no-install-recommends \
        git cmake make gcc g++ gettext unzip curl ca-certificates && \
      git clone --depth 1 --branch v%s https://github.com/neovim/neovim.git /tmp/nvim-src && \
      cd /tmp/nvim-src && \
      make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=/opt/nvim && \
      make install && \
      rm -rf /tmp/nvim-src; \
    fi && \
    ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim`, neovimVersion)
}
