package shellgen

import (
	"os"
	"strings"
	"testing"

	"github.com/rmkohlman/MaestroTerminal/terminalops/plugin"
)

func TestBashGenerator_ShellName(t *testing.T) {
	g := NewBashGenerator()
	if g.ShellName() != "bash" {
		t.Errorf("ShellName() = %q, want %q", g.ShellName(), "bash")
	}
}

func TestBashGenerator_Generate(t *testing.T) {
	boolPtr := func(b bool) *bool { return &b }

	tests := []struct {
		name           string
		config         ShellConfig
		mockFile       func(string) ([]byte, error)
		wantContains   []string
		wantNotContain []string
	}{
		{
			name:     "empty config produces bash header and footer",
			config:   ShellConfig{},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"#!/usr/bin/env bash",
				"generated by DevOpsMaestro",
				"End of .bashrc.workspace",
			},
			wantNotContain: []string{
				"#!/usr/bin/env zsh",
			},
		},
		{
			name: "host bashrc included when present",
			config: ShellConfig{
				HostShellConfigPath: "/fake/.bashrc",
			},
			mockFile: mockReadFile("# My host config\nexport EDITOR=vim\n", nil),
			wantContains: []string{
				"Host .bashrc",
				"# My host config",
				"export EDITOR=vim",
			},
		},
		{
			name: "host bashrc missing gracefully handled",
			config: ShellConfig{
				HostShellConfigPath: "/nonexistent/.bashrc",
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Host .bashrc not found",
			},
		},
		{
			name: "host config skipped when disabled",
			config: ShellConfig{
				HostShellConfigPath: "/fake/.bashrc",
				IncludeHostConfig:   boolPtr(false),
			},
			mockFile: mockReadFile("# Should not appear\n", nil),
			wantNotContain: []string{
				"Host .bashrc",
				"Should not appear",
			},
		},
		{
			name: "env vars use export syntax",
			config: ShellConfig{
				EnvVars: map[string]string{
					"WORKSPACE": "/home/dev/project",
					"APP_ENV":   "development",
				},
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Workspace Environment Variables",
				`export APP_ENV="development"`,
				`export WORKSPACE="/home/dev/project"`,
			},
		},
		{
			name: "prompt config appended",
			config: ShellConfig{
				PromptConfig: `eval "$(starship init bash)"`,
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Prompt Configuration",
				`eval "$(starship init bash)"`,
			},
		},
		{
			name: "workspace name in header",
			config: ShellConfig{
				WorkspaceName: "my-bash-project",
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Workspace: my-bash-project",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := NewBashGenerator()
			g.readFile = tt.mockFile

			output, err := g.Generate(tt.config)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			for _, want := range tt.wantContains {
				if !strings.Contains(output, want) {
					t.Errorf("output should contain %q\nGot:\n%s", want, output)
				}
			}
			for _, notWant := range tt.wantNotContain {
				if strings.Contains(output, notWant) {
					t.Errorf("output should NOT contain %q\nGot:\n%s", notWant, output)
				}
			}
		})
	}
}

func TestBashGenerator_Plugins(t *testing.T) {
	g := NewBashGenerator()
	g.readFile = mockReadFile("", os.ErrNotExist)

	config := ShellConfig{
		Plugins: []*plugin.Plugin{
			{
				Name:    "bash-preexec",
				Repo:    "rcaloras/bash-preexec",
				Manager: plugin.PluginManagerManual,
				Enabled: true,
			},
		},
	}

	output, err := g.Generate(config)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Bash uses conditional source syntax
	if !strings.Contains(output, "if [ -f") {
		t.Error("Bash plugins should use 'if [ -f ...' conditional syntax")
	}
	if !strings.Contains(output, "source") {
		t.Error("Bash plugins should use 'source' command")
	}
	if !strings.Contains(output, "bash-preexec") {
		t.Error("output should contain plugin name")
	}
}

func TestBashGenerator_ImplementsInterface(t *testing.T) {
	var gen ShellGenerator = NewBashGenerator()
	if gen.ShellName() != "bash" {
		t.Error("BashGenerator should implement ShellGenerator")
	}
}
