package shellgen

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// BashGenerator produces .bashrc.workspace file content by compositing
// host shell config, workspace env vars, plugins, and prompt initialization.
type BashGenerator struct {
	// readFile is a hook for testing — defaults to os.ReadFile.
	readFile func(string) ([]byte, error)
}

// Compile-time interface check.
var _ ShellGenerator = (*BashGenerator)(nil)

// NewBashGenerator creates a new BashGenerator.
func NewBashGenerator() *BashGenerator {
	return &BashGenerator{
		readFile: os.ReadFile,
	}
}

// ShellName returns "bash".
func (g *BashGenerator) ShellName() string {
	return "bash"
}

// Generate produces the full .bashrc.workspace content from the given config.
func (g *BashGenerator) Generate(config ShellConfig) (string, error) {
	var sb strings.Builder

	g.writeHeader(&sb, config)
	g.writeHostConfig(&sb, config)
	g.writeEnvVars(&sb, config)
	g.writeShellConfigs(&sb, config)
	g.writePlugins(&sb, config)
	g.writePromptConfig(&sb, config)
	g.writeFooter(&sb)

	return sb.String(), nil
}

// writeHeader writes the file header comment.
func (g *BashGenerator) writeHeader(sb *strings.Builder, config ShellConfig) {
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# .bashrc.workspace — generated by DevOpsMaestro (dvt)\n")
	if config.WorkspaceName != "" {
		sb.WriteString(fmt.Sprintf("# Workspace: %s\n", config.WorkspaceName))
	}
	sb.WriteString("# Do not edit manually — regenerate with: dvt shell generate-workspace\n\n")
}

// writeHostConfig reads and includes the host's .bashrc content.
func (g *BashGenerator) writeHostConfig(sb *strings.Builder, config ShellConfig) {
	if !config.ShouldIncludeHostConfig() {
		return
	}

	path := config.GetHostConfigPath()
	if path == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			sb.WriteString("# Warning: could not determine home directory for host .bashrc\n\n")
			return
		}
		path = home + "/.bashrc"
	}

	data, err := g.readFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			sb.WriteString("# Host .bashrc not found, skipping\n\n")
		} else {
			sb.WriteString(fmt.Sprintf("# Warning: could not read host .bashrc (%s): %v\n\n", path, err))
		}
		return
	}

	sb.WriteString("# === Host .bashrc ===\n")
	content := strings.TrimRight(string(data), "\n")
	sb.WriteString(content)
	sb.WriteString("\n\n")
}

// writeEnvVars writes workspace-specific environment variables using Bash syntax.
func (g *BashGenerator) writeEnvVars(sb *strings.Builder, config ShellConfig) {
	if len(config.EnvVars) == 0 {
		return
	}

	sb.WriteString("# === Workspace Environment Variables ===\n")

	keys := make([]string, 0, len(config.EnvVars))
	for k := range config.EnvVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", k, config.EnvVars[k]))
	}
	sb.WriteString("\n")
}
