package shellgen

import (
	"os"
	"strings"
	"testing"

	"github.com/rmkohlman/MaestroTerminal/terminalops/plugin"
)

func TestFishGenerator_ShellName(t *testing.T) {
	g := NewFishGenerator()
	if g.ShellName() != "fish" {
		t.Errorf("ShellName() = %q, want %q", g.ShellName(), "fish")
	}
}

func TestFishGenerator_Generate(t *testing.T) {
	boolPtr := func(b bool) *bool { return &b }

	tests := []struct {
		name           string
		config         ShellConfig
		mockFile       func(string) ([]byte, error)
		wantContains   []string
		wantNotContain []string
	}{
		{
			name:     "empty config produces fish header and footer",
			config:   ShellConfig{},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"config.fish.workspace",
				"generated by DevOpsMaestro",
				"End of config.fish.workspace",
			},
			wantNotContain: []string{
				"#!/usr/bin/env zsh",
				"#!/usr/bin/env bash",
			},
		},
		{
			name: "host config.fish included when present",
			config: ShellConfig{
				HostShellConfigPath: "/fake/config.fish",
			},
			mockFile: mockReadFile("# My fish config\nset -gx EDITOR vim\n", nil),
			wantContains: []string{
				"Host config.fish",
				"# My fish config",
				"set -gx EDITOR vim",
			},
		},
		{
			name: "host config.fish missing gracefully handled",
			config: ShellConfig{
				HostShellConfigPath: "/nonexistent/config.fish",
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Host config.fish not found",
			},
		},
		{
			name: "host config skipped when disabled",
			config: ShellConfig{
				HostShellConfigPath: "/fake/config.fish",
				IncludeHostConfig:   boolPtr(false),
			},
			mockFile: mockReadFile("# Should not appear\n", nil),
			wantNotContain: []string{
				"Host config.fish ===",
				"Should not appear",
			},
		},
		{
			name: "env vars use fish set -gx syntax",
			config: ShellConfig{
				EnvVars: map[string]string{
					"WORKSPACE": "/home/dev/project",
					"APP_ENV":   "development",
				},
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Workspace Environment Variables",
				`set -gx APP_ENV "development"`,
				`set -gx WORKSPACE "/home/dev/project"`,
			},
			wantNotContain: []string{
				"export ",
			},
		},
		{
			name: "prompt config appended",
			config: ShellConfig{
				PromptConfig: "starship init fish | source",
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Prompt Configuration",
				"starship init fish | source",
			},
		},
		{
			name: "workspace name in header",
			config: ShellConfig{
				WorkspaceName: "my-fish-project",
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Workspace: my-fish-project",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := NewFishGenerator()
			g.readFile = tt.mockFile

			output, err := g.Generate(tt.config)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			for _, want := range tt.wantContains {
				if !strings.Contains(output, want) {
					t.Errorf("output should contain %q\nGot:\n%s", want, output)
				}
			}
			for _, notWant := range tt.wantNotContain {
				if strings.Contains(output, notWant) {
					t.Errorf("output should NOT contain %q\nGot:\n%s", notWant, output)
				}
			}
		})
	}
}

func TestFishGenerator_Plugins(t *testing.T) {
	g := NewFishGenerator()
	g.readFile = mockReadFile("", os.ErrNotExist)

	config := ShellConfig{
		Plugins: []*plugin.Plugin{
			{
				Name:    "fish-greeting",
				Repo:    "user/fish-greeting",
				Manager: plugin.PluginManagerManual,
				Enabled: true,
			},
		},
	}

	output, err := g.Generate(config)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Fish uses "if test -f" conditional syntax
	if !strings.Contains(output, "if test -f") {
		t.Error("Fish plugins should use 'if test -f' conditional syntax")
	}
	if !strings.Contains(output, "source") {
		t.Error("Fish plugins should use 'source' command")
	}
	if !strings.Contains(output, "end") {
		t.Error("Fish plugins should close conditionals with 'end'")
	}
	if !strings.Contains(output, "fish-greeting") {
		t.Error("output should contain plugin name")
	}
}

func TestFishGenerator_NoShebang(t *testing.T) {
	g := NewFishGenerator()
	g.readFile = mockReadFile("", os.ErrNotExist)

	output, err := g.Generate(ShellConfig{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Fish config files don't use shebangs
	if strings.HasPrefix(output, "#!") {
		t.Error("Fish config should NOT have a shebang line")
	}
}

func TestFishGenerator_ImplementsInterface(t *testing.T) {
	var gen ShellGenerator = NewFishGenerator()
	if gen.ShellName() != "fish" {
		t.Error("FishGenerator should implement ShellGenerator")
	}
}
