package shellgen

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// FishGenerator produces config.fish.workspace file content by compositing
// host shell config, workspace env vars, plugins, and prompt initialization.
type FishGenerator struct {
	// readFile is a hook for testing — defaults to os.ReadFile.
	readFile func(string) ([]byte, error)
}

// Compile-time interface check.
var _ ShellGenerator = (*FishGenerator)(nil)

// NewFishGenerator creates a new FishGenerator.
func NewFishGenerator() *FishGenerator {
	return &FishGenerator{
		readFile: os.ReadFile,
	}
}

// ShellName returns "fish".
func (g *FishGenerator) ShellName() string {
	return "fish"
}

// Generate produces the full config.fish.workspace content from the given config.
func (g *FishGenerator) Generate(config ShellConfig) (string, error) {
	var sb strings.Builder

	g.writeHeader(&sb, config)
	g.writeHostConfig(&sb, config)
	g.writeEnvVars(&sb, config)
	g.writeShellConfigs(&sb, config)
	g.writePlugins(&sb, config)
	g.writePromptConfig(&sb, config)
	g.writeFooter(&sb)

	return sb.String(), nil
}

// writeHeader writes the file header comment.
func (g *FishGenerator) writeHeader(sb *strings.Builder, config ShellConfig) {
	sb.WriteString("# config.fish.workspace — generated by DevOpsMaestro (dvt)\n")
	if config.WorkspaceName != "" {
		sb.WriteString(fmt.Sprintf("# Workspace: %s\n", config.WorkspaceName))
	}
	sb.WriteString("# Do not edit manually — regenerate with: dvt shell generate-workspace\n\n")
}

// writeHostConfig reads and includes the host's config.fish content.
func (g *FishGenerator) writeHostConfig(sb *strings.Builder, config ShellConfig) {
	if !config.ShouldIncludeHostConfig() {
		return
	}

	path := config.GetHostConfigPath()
	if path == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			sb.WriteString("# Warning: could not determine home directory for host config.fish\n\n")
			return
		}
		path = home + "/.config/fish/config.fish"
	}

	data, err := g.readFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			sb.WriteString("# Host config.fish not found, skipping\n\n")
		} else {
			sb.WriteString(fmt.Sprintf("# Warning: could not read host config.fish (%s): %v\n\n", path, err))
		}
		return
	}

	sb.WriteString("# === Host config.fish ===\n")
	content := strings.TrimRight(string(data), "\n")
	sb.WriteString(content)
	sb.WriteString("\n\n")
}

// writeEnvVars writes workspace-specific environment variables using Fish syntax.
func (g *FishGenerator) writeEnvVars(sb *strings.Builder, config ShellConfig) {
	if len(config.EnvVars) == 0 {
		return
	}

	sb.WriteString("# === Workspace Environment Variables ===\n")

	keys := make([]string, 0, len(config.EnvVars))
	for k := range config.EnvVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("set -gx %s \"%s\"\n", k, config.EnvVars[k]))
	}
	sb.WriteString("\n")
}
