package shellgen

import (
	"os"
	"strings"
	"testing"

	"github.com/rmkohlman/MaestroTerminal/terminalops/plugin"
	"github.com/rmkohlman/MaestroTerminal/terminalops/shell"
)

// =============================================================================
// Helper: mock readFile for testing
// =============================================================================

func mockReadFile(content string, err error) func(string) ([]byte, error) {
	return func(_ string) ([]byte, error) {
		if err != nil {
			return nil, err
		}
		return []byte(content), nil
	}
}

// =============================================================================
// TestNew
// =============================================================================

func TestNew(t *testing.T) {
	g := New()
	if g == nil {
		t.Fatal("New() returned nil")
	}
	if g.readFile == nil {
		t.Fatal("readFile hook should be set")
	}
}

// =============================================================================
// TestGenerate — table-driven tests
// =============================================================================

func TestGenerate(t *testing.T) {
	boolPtr := func(b bool) *bool { return &b }

	tests := []struct {
		name           string
		config         ShellConfig
		mockFile       func(string) ([]byte, error)
		wantContains   []string
		wantNotContain []string
	}{
		{
			name:     "empty config produces header and footer",
			config:   ShellConfig{},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"#!/usr/bin/env zsh",
				"generated by DevOpsMaestro",
				"End of .zshrc.workspace",
			},
		},
		{
			name: "host zshrc included when present",
			config: ShellConfig{
				HostZshrcPath: "/fake/.zshrc",
			},
			mockFile: mockReadFile("# My host config\nexport EDITOR=vim\n", nil),
			wantContains: []string{
				"Host .zshrc",
				"# My host config",
				"export EDITOR=vim",
			},
		},
		{
			name: "host zshrc missing gracefully handled",
			config: ShellConfig{
				HostZshrcPath: "/nonexistent/.zshrc",
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Host .zshrc not found",
			},
			wantNotContain: []string{
				"export EDITOR",
			},
		},
		{
			name: "host zshrc skipped when disabled",
			config: ShellConfig{
				HostZshrcPath:    "/fake/.zshrc",
				IncludeHostZshrc: boolPtr(false),
			},
			mockFile: mockReadFile("# Should not appear\n", nil),
			wantNotContain: []string{
				"Host .zshrc",
				"Should not appear",
			},
		},
		{
			name: "env vars injected and sorted",
			config: ShellConfig{
				EnvVars: map[string]string{
					"WORKSPACE": "/home/dev/project",
					"APP_ENV":   "development",
				},
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Workspace Environment Variables",
				`export APP_ENV="development"`,
				`export WORKSPACE="/home/dev/project"`,
			},
		},
		{
			name: "prompt config appended",
			config: ShellConfig{
				PromptConfig: `eval "$(starship init zsh)"`,
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Prompt Configuration",
				`eval "$(starship init zsh)"`,
			},
		},
		{
			name: "workspace name in header",
			config: ShellConfig{
				WorkspaceName: "my-project",
			},
			mockFile: mockReadFile("", os.ErrNotExist),
			wantContains: []string{
				"Workspace: my-project",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := New()
			g.readFile = tt.mockFile

			output, err := g.Generate(tt.config)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			for _, want := range tt.wantContains {
				if !strings.Contains(output, want) {
					t.Errorf("output should contain %q\nGot:\n%s", want, output)
				}
			}
			for _, notWant := range tt.wantNotContain {
				if strings.Contains(output, notWant) {
					t.Errorf("output should NOT contain %q\nGot:\n%s", notWant, output)
				}
			}
		})
	}
}

// =============================================================================
// TestGenerate_WithPlugins
// =============================================================================

func TestGenerate_WithPlugins(t *testing.T) {
	g := New()
	g.readFile = mockReadFile("", os.ErrNotExist)

	config := ShellConfig{
		Plugins: []*plugin.Plugin{
			{
				Name:     "zsh-autosuggestions",
				Repo:     "zsh-users/zsh-autosuggestions",
				Manager:  plugin.PluginManagerManual,
				Priority: 10,
				Enabled:  true,
			},
			{
				Name:     "zsh-syntax-highlighting",
				Repo:     "zsh-users/zsh-syntax-highlighting",
				Manager:  plugin.PluginManagerManual,
				Priority: 20,
				Enabled:  true,
			},
		},
	}

	output, err := g.Generate(config)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Plugins should appear
	if !strings.Contains(output, "zsh-autosuggestions") {
		t.Error("output should contain zsh-autosuggestions")
	}
	if !strings.Contains(output, "zsh-syntax-highlighting") {
		t.Error("output should contain zsh-syntax-highlighting")
	}

	// Verify load order — autosuggestions (priority 10) before highlighting (priority 20)
	sugIdx := strings.Index(output, "zsh-autosuggestions")
	hlIdx := strings.Index(output, "zsh-syntax-highlighting")
	if sugIdx > hlIdx {
		t.Error("zsh-autosuggestions should appear before zsh-syntax-highlighting (load order)")
	}
}

// =============================================================================
// TestGenerate_DisabledPluginsSkipped
// =============================================================================

func TestGenerate_DisabledPluginsSkipped(t *testing.T) {
	g := New()
	g.readFile = mockReadFile("", os.ErrNotExist)

	config := ShellConfig{
		Plugins: []*plugin.Plugin{
			{
				Name:    "disabled-plugin",
				Repo:    "user/disabled-plugin",
				Manager: plugin.PluginManagerManual,
				Enabled: false,
			},
		},
	}

	output, err := g.Generate(config)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// The plugin generator still gets called but filters disabled plugins
	if strings.Contains(output, "disabled-plugin") {
		t.Error("disabled plugins should not appear in output")
	}
}

// =============================================================================
// TestGenerate_WithShellConfigs
// =============================================================================

func TestGenerate_WithShellConfigs(t *testing.T) {
	g := New()
	g.readFile = mockReadFile("", os.ErrNotExist)

	config := ShellConfig{
		ShellConfigs: []*shell.Shell{
			{
				Name:      "dev-aliases",
				ShellType: shell.ShellTypeZsh,
				Enabled:   true,
				Aliases: []shell.Alias{
					{Name: "ll", Command: "ls -la"},
				},
			},
		},
	}

	output, err := g.Generate(config)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(output, "alias ll='ls -la'") {
		t.Error("output should contain shell alias")
	}
}

// =============================================================================
// TestGenerate_FullComposite
// =============================================================================

func TestGenerate_FullComposite(t *testing.T) {
	g := New()
	g.readFile = mockReadFile("# Host zshrc content\n", nil)

	config := ShellConfig{
		HostZshrcPath: "/home/user/.zshrc",
		WorkspaceName: "test-workspace",
		EnvVars: map[string]string{
			"PROJECT_ROOT": "/workspace",
		},
		Plugins: []*plugin.Plugin{
			{
				Name:    "zsh-completions",
				Repo:    "zsh-users/zsh-completions",
				Manager: plugin.PluginManagerManual,
				Enabled: true,
			},
		},
		ShellConfigs: []*shell.Shell{
			{
				Name:      "basics",
				ShellType: shell.ShellTypeZsh,
				Enabled:   true,
				Env: []shell.EnvVar{
					{Name: "LANG", Value: "en_US.UTF-8"},
				},
			},
		},
		PromptConfig: `eval "$(starship init zsh)"`,
	}

	output, err := g.Generate(config)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify all sections present and in correct order
	sections := []string{
		"Host .zshrc",
		"Host zshrc content",
		"Workspace Environment Variables",
		"PROJECT_ROOT",
		"LANG",
		"zsh-completions",
		"Prompt Configuration",
		"starship init zsh",
		"End of .zshrc.workspace",
	}

	lastIdx := -1
	for _, section := range sections {
		idx := strings.Index(output, section)
		if idx == -1 {
			t.Errorf("output missing section: %q", section)
			continue
		}
		if idx <= lastIdx {
			t.Errorf("section %q should appear after previous section", section)
		}
		lastIdx = idx
	}
}

// =============================================================================
// TestShellConfig_ShouldIncludeHostZshrc
// =============================================================================

func TestShellConfig_ShouldIncludeHostZshrc(t *testing.T) {
	boolPtr := func(b bool) *bool { return &b }

	tests := []struct {
		name     string
		config   ShellConfig
		expected bool
	}{
		{"nil defaults to true", ShellConfig{}, true},
		{"explicit true", ShellConfig{IncludeHostZshrc: boolPtr(true)}, true},
		{"explicit false", ShellConfig{IncludeHostZshrc: boolPtr(false)}, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.config.ShouldIncludeHostZshrc()
			if got != tt.expected {
				t.Errorf("ShouldIncludeHostZshrc() = %v, want %v", got, tt.expected)
			}
		})
	}
}
