package shellgen

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// ZshrcGenerator produces .zshrc.workspace file content by compositing
// host shell config, workspace env vars, plugins, and prompt initialization.
type ZshrcGenerator struct {
	// readFile is a hook for testing — defaults to os.ReadFile.
	readFile func(string) ([]byte, error)
}

// New creates a new ZshrcGenerator.
func New() *ZshrcGenerator {
	return &ZshrcGenerator{
		readFile: os.ReadFile,
	}
}

// Generate produces the full .zshrc.workspace content from the given config.
func (g *ZshrcGenerator) Generate(config ShellConfig) (string, error) {
	var sb strings.Builder

	g.writeHeader(&sb, config)
	g.writeHostZshrc(&sb, config)
	g.writeEnvVars(&sb, config)
	g.writeShellConfigs(&sb, config)
	g.writePlugins(&sb, config)
	g.writePromptConfig(&sb, config)
	g.writeFooter(&sb)

	return sb.String(), nil
}

// writeHeader writes the file header comment.
func (g *ZshrcGenerator) writeHeader(sb *strings.Builder, config ShellConfig) {
	sb.WriteString("#!/usr/bin/env zsh\n")
	sb.WriteString("# .zshrc.workspace — generated by DevOpsMaestro (dvt)\n")
	if config.WorkspaceName != "" {
		sb.WriteString(fmt.Sprintf("# Workspace: %s\n", config.WorkspaceName))
	}
	sb.WriteString("# Do not edit manually — regenerate with: dvt shell generate-workspace\n\n")
}

// writeHostZshrc reads and includes the host's .zshrc content.
func (g *ZshrcGenerator) writeHostZshrc(sb *strings.Builder, config ShellConfig) {
	if !config.ShouldIncludeHostZshrc() {
		return
	}

	path := config.HostZshrcPath
	if path == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			sb.WriteString("# Warning: could not determine home directory for host .zshrc\n\n")
			return
		}
		path = home + "/.zshrc"
	}

	data, err := g.readFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			sb.WriteString("# Host .zshrc not found, skipping\n\n")
		} else {
			sb.WriteString(fmt.Sprintf("# Warning: could not read host .zshrc (%s): %v\n\n", path, err))
		}
		return
	}

	sb.WriteString("# === Host .zshrc ===\n")
	content := strings.TrimRight(string(data), "\n")
	sb.WriteString(content)
	sb.WriteString("\n\n")
}

// writeEnvVars writes workspace-specific environment variables.
func (g *ZshrcGenerator) writeEnvVars(sb *strings.Builder, config ShellConfig) {
	if len(config.EnvVars) == 0 {
		return
	}

	sb.WriteString("# === Workspace Environment Variables ===\n")

	// Sort keys for deterministic output
	keys := make([]string, 0, len(config.EnvVars))
	for k := range config.EnvVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", k, config.EnvVars[k]))
	}
	sb.WriteString("\n")
}
