// Package profile provides the TerminalProfile type that aggregates
// prompt, plugins, and shell configuration into a complete terminal setup.
package profile

import (
	"fmt"
	"strings"

	"devopsmaestro/pkg/terminalops/plugin"
	"devopsmaestro/pkg/terminalops/prompt"
	"devopsmaestro/pkg/terminalops/shell"
)

// Generator generates complete terminal configuration from a Profile.
type Generator struct {
	promptGen *prompt.StarshipGenerator
	pluginGen *plugin.ZshGenerator
	shellGen  *shell.Generator
}

// NewGenerator creates a new profile Generator.
func NewGenerator(pluginDir string) *Generator {
	return &Generator{
		promptGen: prompt.NewStarshipGenerator(),
		pluginGen: plugin.NewZshGenerator(pluginDir),
		shellGen:  shell.NewGenerator(),
	}
}

// GeneratedConfig holds all generated configuration files.
type GeneratedConfig struct {
	// StarshipTOML is the starship.toml content
	StarshipTOML string
	// ZshrcPlugins is the plugin loading section for .zshrc
	ZshrcPlugins string
	// ZshrcShell is the shell config section for .zshrc
	ZshrcShell string
	// ZshrcFull is the complete .zshrc content
	ZshrcFull string
	// InstallScript is a shell script to install plugins
	InstallScript string
}

// Generate creates all configuration files from a Profile.
func (g *Generator) Generate(p *Profile) (*GeneratedConfig, error) {
	if p == nil {
		return nil, fmt.Errorf("profile is nil")
	}
	if !p.Enabled {
		return &GeneratedConfig{}, nil
	}

	config := &GeneratedConfig{}
	var zshrcParts []string

	// Header
	zshrcParts = append(zshrcParts, fmt.Sprintf(`# Terminal configuration generated by DevOpsMaestro
# Profile: %s
# Description: %s
#
# This file should be sourced from your .zshrc:
#   source ~/.config/dvm/terminal/%s.zsh
`, p.Name, p.Description, p.Name))

	// Generate Starship config
	if p.Prompt != nil && p.Prompt.IsStarship() {
		starship, err := g.promptGen.Generate(p.Prompt)
		if err != nil {
			return nil, fmt.Errorf("failed to generate starship config: %w", err)
		}
		config.StarshipTOML = starship

		// Add starship init to zshrc
		zshrcParts = append(zshrcParts, `# === Starship Prompt ===
# Ensure starship is installed: curl -sS https://starship.rs/install.sh | sh
if command -v starship &> /dev/null; then
  eval "$(starship init zsh)"
fi
`)
	}

	// Generate shell config
	if p.Shell != nil {
		shellConfig, err := g.shellGen.Generate(p.Shell)
		if err != nil {
			return nil, fmt.Errorf("failed to generate shell config: %w", err)
		}
		config.ZshrcShell = shellConfig
		zshrcParts = append(zshrcParts, shellConfig)
	}

	// Generate plugin config
	if len(p.Plugins) > 0 {
		pluginConfig, err := g.pluginGen.Generate(p.Plugins)
		if err != nil {
			return nil, fmt.Errorf("failed to generate plugin config: %w", err)
		}
		config.ZshrcPlugins = pluginConfig
		zshrcParts = append(zshrcParts, pluginConfig)

		// Generate install script
		config.InstallScript = g.pluginGen.GenerateInstallScript(p.Plugins)
	}

	config.ZshrcFull = strings.Join(zshrcParts, "\n")

	return config, nil
}

// GenerateZshrc generates a complete .zshrc file from the profile.
func (g *Generator) GenerateZshrc(p *Profile) (string, error) {
	config, err := g.Generate(p)
	if err != nil {
		return "", err
	}
	return config.ZshrcFull, nil
}

// DefaultProfile returns a sensible default terminal profile.
func DefaultProfile() *Profile {
	return &Profile{
		Name:        "default",
		Description: "Default DevOpsMaestro terminal profile",
		Enabled:     true,
		Prompt: &prompt.Prompt{
			Name:        "default-prompt",
			Type:        prompt.PromptTypeStarship,
			Description: "Clean developer prompt",
			Format:      "$directory$git_branch$git_status$character",
			Character: &prompt.CharacterConfig{
				SuccessSymbol: "[❯](bold green)",
				ErrorSymbol:   "[❯](bold red)",
			},
			Modules: map[string]prompt.ModuleConfig{
				"directory": {
					Options: map[string]any{
						"truncation_length": 3,
						"truncate_to_repo":  true,
					},
				},
				"git_branch": {
					Format: "[$branch]($style) ",
					Style:  "bold purple",
				},
				"git_status": {
					Format: "[$all_status$ahead_behind]($style) ",
					Style:  "bold red",
				},
			},
			Enabled: true,
		},
		Plugins: []*plugin.Plugin{
			{
				Name:        "zsh-autosuggestions",
				Description: "Fish-like autosuggestions for zsh",
				Repo:        "zsh-users/zsh-autosuggestions",
				Manager:     plugin.PluginManagerManual,
				LoadMode:    plugin.LoadModeImmediate,
				Enabled:     true,
				Priority:    10,
			},
			{
				Name:        "zsh-syntax-highlighting",
				Description: "Fish-like syntax highlighting for zsh",
				Repo:        "zsh-users/zsh-syntax-highlighting",
				Manager:     plugin.PluginManagerManual,
				LoadMode:    plugin.LoadModeImmediate,
				Enabled:     true,
				Priority:    20,
			},
		},
		Shell: &shell.Shell{
			Name:      "default-shell",
			ShellType: shell.ShellTypeZsh,
			Options:   shell.DefaultZshOptions(),
			History:   shell.DefaultHistoryConfig(),
			Aliases:   append(shell.CommonAliases(), shell.DevAliases()...),
			Enabled:   true,
		},
	}
}

// MinimalProfile returns a minimal terminal profile with just the essentials.
func MinimalProfile() *Profile {
	return &Profile{
		Name:        "minimal",
		Description: "Minimal terminal profile - just Starship prompt",
		Enabled:     true,
		Prompt: &prompt.Prompt{
			Name:        "minimal-prompt",
			Type:        prompt.PromptTypeStarship,
			Description: "Minimal Starship prompt",
			Format:      "$directory$character",
			Character: &prompt.CharacterConfig{
				SuccessSymbol: "[❯](green)",
				ErrorSymbol:   "[❯](red)",
			},
			Modules: map[string]prompt.ModuleConfig{
				"directory": {
					Options: map[string]any{
						"truncation_length": 2,
					},
				},
			},
			Enabled: true,
		},
		Shell: &shell.Shell{
			Name:      "minimal-shell",
			ShellType: shell.ShellTypeZsh,
			History:   shell.DefaultHistoryConfig(),
			Enabled:   true,
		},
	}
}

// PowerUserProfile returns a feature-rich terminal profile.
func PowerUserProfile() *Profile {
	return &Profile{
		Name:        "power-user",
		Description: "Feature-rich terminal profile for power users",
		Enabled:     true,
		Prompt: &prompt.Prompt{
			Name:        "power-prompt",
			Type:        prompt.PromptTypeStarship,
			Description: "Information-rich Starship prompt",
			Format:      "$username$hostname$directory$git_branch$git_status$golang$nodejs$python$rust$docker_context$kubernetes$cmd_duration$line_break$character",
			Character: &prompt.CharacterConfig{
				SuccessSymbol: "[❯](bold green)",
				ErrorSymbol:   "[✗](bold red)",
				ViCmdSymbol:   "[❮](bold yellow)",
			},
			Modules: map[string]prompt.ModuleConfig{
				"directory": {
					Options: map[string]any{
						"truncation_length": 4,
						"truncate_to_repo":  true,
					},
				},
				"git_branch": {
					Symbol: " ",
					Style:  "bold purple",
				},
				"git_status": {
					Style: "bold red",
				},
				"golang": {
					Symbol: " ",
				},
				"nodejs": {
					Symbol: " ",
				},
				"python": {
					Symbol: " ",
				},
				"rust": {
					Symbol: " ",
				},
				"docker_context": {
					Symbol: " ",
				},
				"kubernetes": {
					Disabled: false,
					Symbol:   "☸ ",
				},
				"cmd_duration": {
					Options: map[string]any{
						"min_time": 2000,
					},
				},
			},
			Enabled: true,
		},
		Plugins: []*plugin.Plugin{
			{
				Name:        "zsh-autosuggestions",
				Description: "Fish-like autosuggestions",
				Repo:        "zsh-users/zsh-autosuggestions",
				Manager:     plugin.PluginManagerManual,
				Enabled:     true,
				Priority:    10,
			},
			{
				Name:        "zsh-syntax-highlighting",
				Description: "Fish-like syntax highlighting",
				Repo:        "zsh-users/zsh-syntax-highlighting",
				Manager:     plugin.PluginManagerManual,
				Enabled:     true,
				Priority:    20,
			},
			{
				Name:        "zsh-completions",
				Description: "Additional completion definitions",
				Repo:        "zsh-users/zsh-completions",
				Manager:     plugin.PluginManagerManual,
				Enabled:     true,
				Priority:    5,
			},
			{
				Name:        "fzf-tab",
				Description: "Replace zsh completion with fzf",
				Repo:        "Aloxaf/fzf-tab",
				Manager:     plugin.PluginManagerManual,
				Enabled:     true,
				Priority:    30,
			},
		},
		Shell: &shell.Shell{
			Name:      "power-shell",
			ShellType: shell.ShellTypeZsh,
			Options:   shell.DefaultZshOptions(),
			History:   shell.DefaultHistoryConfig(),
			Aliases:   append(shell.CommonAliases(), shell.DevAliases()...),
			Env: []shell.EnvVar{
				{Name: "EDITOR", Value: "nvim", Description: "Default editor"},
				{Name: "VISUAL", Value: "nvim", Description: "Visual editor"},
			},
			Enabled: true,
		},
	}
}
